'use client';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {createPortal} from 'react-dom';
import type {StudyPlugin} from './registry';
import {DEMO_PAPER_ALEXNET,PAPER_SLOTS,exportPaperVocabulary,paperTokens,parsePaperStudyData,selectPaperRange,togglePaperWord,type PaperStudyData,type PaperDraft,type PaperSlot,type PaperWord,type VocabularyReceipt} from '../paper-study';
import {loadPaperMaterials,openPaperDraft,savePaperMaterial,type PaperDraftSession,type PaperMaterial} from '../paper-draft-store';
import {type PaperVocabularyClient} from '../paper-vocabulary-client';
import {useOptionalStudyAIWorkspace} from '../components/ai-sidebar/study-ai-workspace';
import {PaperSourcesPanel,PaperNoteSavePanel} from '../paper-sources-panel';
import {type PaperLibraryClient} from '../paper-library-client';
import {DISCIPLINES} from '../learning-catalog';
import './paper.css';
import {StudyGuidance,StudyGuidanceHelp} from '../study-guidance';
import {PaperWorkspacePanels} from '../paper-workspace-panels';
import {PAPER_SLOT_TEMPLATES,paperTemplate,currentPaperSlots,setPaperTemplate,setPaperSlot,paperReviewerActions,paperSelfcheckLabels} from '../paper-slot-templates';
import {readingNoteMarkdown} from '../paper-reading-note';
import {buildPaperReview} from '../paper-review-budget';
import {copyTextSafely} from '../clipboard';
import {figureReferences} from '../paper-figures';
import {PaperFigurePanel} from '../components/paper-figure-panel';
import {useManagedDialog} from '../use-managed-dialog';
import {PaperSelectionToolbar} from '../components/paper-selection-toolbar';
import {ingestPaperVocabulary,paperVocabularyReceiptMessage,type PaperVocabularyReadback} from '../paper-vocabulary-ingest';
import {paperRetestSeeds} from '../../src/domain/practice-candidates';
import {CandidateLauncher} from '../../src/features/remediation';
import {registerStudyNavigationGuard} from '../study-navigation-guard';
import '../../src/features/remediation/remediation.css';
export {DEMO_PAPER_ALEXNET} from '../paper-study';
export type PaperServices={owner:string;library:string;localLibraryId?:string;accountLibraryId?:string;client?:PaperVocabularyClient;libraryClient?:PaperLibraryClient;onSources?:()=>void;isCurrent?:()=>boolean;refreshVocabulary?:(entries:PaperWord[],localLibraryId:string)=>Promise<PaperVocabularyReadback>};
function download(name:string,text:string,type='text/markdown'){const url=URL.createObjectURL(new Blob([text],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function PaperEditor({paper,session,services}:{paper:PaperStudyData;session:PaperDraftSession;services:PaperServices}){
 const state=useSyncExternalStore(session.subscribe,session.snapshot,session.snapshot),draft=state.draft,ai=useOptionalStudyAIWorkspace();
 const paragraphs=paper.sections.flatMap(section=>section.paragraphs.map(paragraph=>({section,paragraph}))),position=Math.min(draft.position,paragraphs.length-1),{section,paragraph}=paragraphs[position];
 const [message,setMessage]=useState(''),[hidden,setHidden]=useState(false),[aiText,setAiText]=useState(''),[aiBusy,setAiBusy]=useState(false),[prompt,setPrompt]=useState(''),[timer,setTimer]=useState<number|null>(null),[remaining,setRemaining]=useState(0);
 const [selection,setSelection]=useState<{word:PaperWord;focus:boolean}|null>(null),[readback,setReadback]=useState<{requestId:string;value:PaperVocabularyReadback}|null>(null),[checkingVocabulary,setCheckingVocabulary]=useState(false);
 const [reviewScopeNotice,setReviewScopeNotice]=useState('');
 const [figureId,setFigureId]=useState<string|null>(null),figureTrigger=useRef<HTMLElement|null>(null);
 const [activePanel,setActivePanel]=useState<0|1>(0),figureReturnPanel=useRef<0|1>(0);
 const template=paperTemplate(draft.slotTemplate);
 const figure=paper.figures?.find(f=>f.assetId===figureId),references=figureReferences(paragraph.rawEn,paper.figures);
 const readingTokens:{text:string;start:number;end:number;isWord:boolean;assetId?:string}[]=[];let textStart=0;
 for(const ref of references){readingTokens.push(...paperTokens(paragraph.rawEn.slice(textStart,ref.start)).map(t=>({...t,start:t.start+textStart,end:t.end+textStart})),{text:paragraph.rawEn.slice(ref.start,ref.end),start:ref.start,end:ref.end,isWord:false,assetId:ref.assetId});textStart=ref.end;}
 readingTokens.push(...paperTokens(paragraph.rawEn.slice(textStart)).map(t=>({...t,start:t.start+textStart,end:t.end+textStart})));
 const openFigure=(id:string,element:HTMLElement)=>{figureTrigger.current=element;figureReturnPanel.current=element.closest('.paper-reading')?0:1;setSelection(null);setActivePanel(1);setFigureId(id);};
 const figureNavigation=useRef<HTMLElement>(null);
 const closeFigure=()=>{const target=figureTrigger.current?.isConnected&&figureTrigger.current.dataset.figureId===figureId?figureTrigger.current:Array.from(figureNavigation.current?.querySelectorAll<HTMLElement>('[data-figure-id]')??[]).find(node=>node.dataset.figureId===figureId);setFigureId(null);setActivePanel(figureReturnPanel.current);requestAnimationFrame(()=>target?.focus({preventScroll:true}));};
 const tray=useRef<HTMLElement>(null),readbackRun=useRef(0),busy=session.isExclusive('vocabulary-ingest');
 const raw=useRef<HTMLParagraphElement>(null),pointer=useRef<{x:number;y:number;start:number|null}|null>(null),suppress=useRef(false),anchor=useRef<{start:number;end:number}|null>(null),controller=useRef<AbortController|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(timer===null)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((timer-Date.now())/1000)));tick();const id=setInterval(tick,1000);return()=>clearInterval(id);},[timer]);
 useEffect(()=>()=>{controller.current?.abort();},[ai?.service,ai?.settings?.revision]);
 const update=(change:(draft:PaperDraft)=>PaperDraft)=>{void session.update(change);};
 function choose(start:number,end:number,focus=false){const selected=selectPaperRange(paper,paragraph.id,start,end);if(!selected){setMessage('请在同一句内选取 1–8 个完整词。');return;}if(draft.sourceNoteOverride!==undefined)selected.sourceNote=draft.sourceNoteOverride;try{let kept=false;update(d=>{const next=togglePaperWord(d,selected);kept=next.selected.some(word=>word.id===selected.id);return next;});setSelection(kept?{word:selected,focus}:null);setMessage(kept?(selected.meaning?'已带入本段释义，可核对后收录。':'请补充这句话中的意思，再收录。'):'已从本次选择移除。');}catch(error){setMessage(String(error));}}
 function closeSelection(restore=false){if(restore&&selection)raw.current?.querySelector<HTMLElement>(`button[data-paper-start="${selection.word.start}"]`)?.focus({preventScroll:true});setSelection(null);}
 function showTray(){closeSelection();tray.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});tray.current?.focus({preventScroll:true});}
 function finishDrag(event:React.PointerEvent){const begin=pointer.current;pointer.current=null;if(!begin||Math.hypot(event.clientX-begin.x,event.clientY-begin.y)<5)return;const endToken=(event.target as Element).closest<HTMLElement>('button[data-paper-start]');if(begin.start!==null&&endToken&&raw.current?.contains(endToken)){choose(Math.min(begin.start,Number(endToken.dataset.paperStart)),Math.max(begin.start+1,Number(endToken.dataset.paperEnd)));suppress.current=true;document.getSelection()?.removeAllRanges();return;}const selection=document.getSelection(),node=raw.current;if(!selection||selection.isCollapsed||!node||!selection.anchorNode||!selection.focusNode||!node.contains(selection.anchorNode)||!node.contains(selection.focusNode))return;const range=selection.getRangeAt(0),prefix=range.cloneRange();prefix.selectNodeContents(node);prefix.setEnd(range.startContainer,range.startOffset);const start=prefix.toString().length,end=start+range.toString().length;choose(start,end);suppress.current=true;selection.removeAllRanges();}
 async function refreshVocabulary(entries:PaperWord[],receipt:VocabularyReceipt){
  const requestId=receipt.requestId;
  if(!services.refreshVocabulary||!entries.length)return;
  const run=++readbackRun.current;
  if(alive.current)setCheckingVocabulary(true);
  try{const value=await services.refreshVocabulary(entries,receipt.localLibraryId);if(alive.current&&run===readbackRun.current&&session.snapshot().draft.receipt?.requestId===requestId)setReadback({requestId,value});}
  catch{if(alive.current&&run===readbackRun.current&&session.snapshot().draft.receipt?.requestId===requestId)setReadback({requestId,value:{status:'unavailable',matched:0,total:entries.length,itemKeys:[],mode:services.accountLibraryId?'account':'local'}});}
  finally{if(alive.current&&run===readbackRun.current)setCheckingVocabulary(false);}
 }
 async function ingest(entryIds?:string[],retry=false){if(busy)return;setMessage('正在核对本机词库…');try{
  const result=await ingestPaperVocabulary(session,{owner:services.owner,expected:services,client:services.client,libraryClient:services.libraryClient,entryIds,retry,isCurrent:()=>alive.current&&services.isCurrent?.()!==false});
  if(!alive.current)return;setMessage(paperVocabularyReceiptMessage(result.receipt));
  const entries=result.request.entries.filter(word=>result.receipt.results.some(row=>row.id===word.id&&row.status!=='conflict'));
  await refreshVocabulary(entries,result.receipt);
 }catch(error){if(alive.current)setMessage(`${error instanceof Error?error.message:String(error)}${session.snapshot().draft.pending?' 原请求已保留，请重试核对。':''}`);}}
 async function reviewer(action:string){
  controller.current?.abort();const c=new AbortController();controller.current=c;setAiBusy(false);setAiText('');
  let request;try{request=buildPaperReview(action,paper,paragraph,draft);}catch(error){setReviewScopeNotice(error instanceof Error?error.message:'请缩小本次审阅范围。');return;}
  setPrompt(request.prompt);setReviewScopeNotice(request.notice);
  if(!ai?.settings?.enabled||!ai.settings.configured){setMessage('可复制审稿问题；连接 AI 后再提问。');return;}
  if(request.truncated&&!window.confirm(request.notice+' 是否发送这次节选？'))return;
  setAiBusy(true);
  try{for await(const event of ai.service.chat({requestId:crypto.randomUUID(),provider:ai.settings.provider,model:ai.settings.model,settingsRevision:ai.settings.revision,context:request.context,messages:[{role:'user',content:request.prompt}]},c.signal)){
   if(c.signal.aborted||!alive.current||controller.current!==c)return;if(event.type==='delta')setAiText(text=>text+event.text);
  }}catch(error){if(!c.signal.aborted&&alive.current&&controller.current===c)setAiText(`AI 暂不可用：${String(error)}。可复制下方问题继续。`);}
  finally{if(alive.current&&controller.current===c)setAiBusy(false);}
 }
 if(!state.ready)return <p role="status">正在读取论文草稿…</p>;
 const toolbarWord=selection&&(draft.selected.find(word=>word.id===selection.word.id)??draft.ingestedVocabulary?.find(word=>word.id===selection.word.id)??draft.pending?.entries.find(word=>word.id===selection.word.id));
 const currentReadback=readback?.requestId===draft.receipt?.requestId?readback?.value:null;
 const receiptEntries=(draft.ingestedVocabulary??[]).filter(word=>draft.receipt?.results.some(row=>row.id===word.id&&row.status!=='conflict'));
 return <div className="paper-workshop" role="group" aria-label="论文精读工作区">
  <header className="paper-heading"><div><span className="paper-eyebrow">READ · QUESTION · RECONSTRUCT</span><h1>{paper.title}</h1><p>{[paper.authors?.join(', '),paper.year,paper.venue].filter(Boolean).join(' · ')}</p></div><span className="paper-save-state" role="status">{state.error?'草稿待导出':state.saving?'正在保存…':'草稿已就绪'}</span></header>
  <StudyGuidance topic="paper" context={{guidanceScope:services.owner,guidanceInOptions:true}} engaged={Boolean(draft.position||draft.selected.length||Object.values(draft.summaries).some(Boolean)||currentPaperSlots(draft).some(slot=>Boolean(slot.value)))}/>
  {state.error&&<p role="alert">{state.error} 当前输入仍在本页，请导出完整草稿。</p>}
  <div className="paper-topbar"><span>微段 {position+1} / {paragraphs.length} · {paragraph.pageNumber?`PDF 第 ${paragraph.pageNumber} 页`:'按原文微段定位'}</span><div><button disabled={position===0} onClick={()=>{controller.current?.abort();setAiBusy(false);setAiText('');anchor.current=null;setSelection(null);update(d=>({...d,position:position-1}));}}>上一段</button><button disabled={position===paragraphs.length-1} onClick={()=>{controller.current?.abort();setAiBusy(false);setAiText('');anchor.current=null;setSelection(null);update(d=>({...d,position:position+1}));}}>下一段</button></div></div>
  <PaperWorkspacePanels active={activePanel} onActiveChange={index=>{setSelection(null);pointer.current=null;setActivePanel(index);}} reading={<section className="paper-reading"><h2>{section.title}</h2><div className="paper-reading-tools"><StudyGuidanceHelp kind="paper"/><button onClick={()=>{setSelection(null);setHidden(x=>!x);}}>{hidden?'显示原文':'隐藏原文，闭卷回忆'}</button></div>
   {hidden?<div className="paper-closed">原文已隐藏。用自己的话重建主张、机制与证据。</div>:<p ref={raw} className="paper-raw" lang="en" onPointerDown={e=>{const token=(e.target as Element).closest<HTMLElement>('button[data-paper-start]');pointer.current={x:e.clientX,y:e.clientY,start:token?Number(token.dataset.paperStart):null};suppress.current=false;}} onPointerUp={finishDrag} onPointerCancel={()=>{pointer.current=null;suppress.current=false;}}>{readingTokens.map(t=>t.assetId?<button key={t.start} type="button" className="paper-inline-figure" data-figure-id={t.assetId} onClick={event=>openFigure(t.assetId!,event.currentTarget)} aria-label={`查看图表 ${t.text}`}>{t.text}</button>:t.isWord?<button key={t.start} data-paper-start={t.start} data-paper-end={t.end} type="button" aria-pressed={draft.selected.some(x=>x.paragraphId===paragraph.id&&x.start<=t.start&&x.end>=t.end)} onClick={e=>{if(suppress.current){suppress.current=false;return;}if(e.shiftKey&&anchor.current!==null)choose(Math.min(anchor.current.start,t.start),Math.max(anchor.current.end,t.end),e.detail===0);else{choose(t.start,t.end,e.detail===0);anchor.current={start:t.start,end:t.end};}}}>{t.text}</button>:<span key={t.start}>{t.text}</span>)}</p>}
   {!hidden&&references.length>0&&<nav className="paper-figure-references" aria-label="本段图表引用">{references.map(ref=><button key={ref.start} data-figure-id={ref.assetId} type="button" onClick={event=>openFigure(ref.assetId,event.currentTarget)}>{paragraph.rawEn.slice(ref.start,ref.end)} ↗</button>)}</nav>}
   {!hidden&&toolbarWord&&toolbarWord.paragraphId===paragraph.id&&<PaperSelectionToolbar word={toolbarWord} raw={raw} selected={draft.selected.some(word=>word.id===toolbarWord.id)} busy={busy} pending={Boolean(draft.pending)} connected={Boolean(services.client)} focusOnOpen={selection?.focus??false} message={message} error={state.error||undefined} onMeaning={meaning=>update(d=>({...d,selected:d.selected.map(word=>word.id===toolbarWord.id?{...word,meaning}:word)}))} onIngest={()=>void ingest([toolbarWord.id])} onRetry={()=>void ingest(undefined,true)} onClose={closeSelection} onTray={showTray} onConnect={services.onSources}/>}
   {!hidden&&!!paragraph.scaffoldHints?.length&&<details><summary>需要一点提示</summary>{paragraph.scaffoldHints.map(h=><p key={h}>{h}</p>)}</details>}
   <label className="paper-label">这段讲了什么？<textarea maxLength={4000} value={draft.summaries[paragraph.id]??''} onChange={e=>update(d=>({...d,summaries:{...d.summaries,[paragraph.id]:e.target.value}}))} placeholder="先凭记忆概括，再展开原文核对。"/></label>
   <p className="paper-bridge">章节桥接：{section.sectionBridgeQuestion??'这一段如何回应前面的研究问题？'}</p>
   <section ref={tray} className="paper-tray" tabIndex={-1} aria-label="已选词托盘"><h2>本次已选生词 <span>{draft.selected.length}</span></h2>{draft.selected.length===0?<p>尚未选词。演示词不会自动加入你的词库。</p>:draft.selected.map(word=><article key={word.id}><div><strong lang="en">{word.term}</strong><button aria-label={`删除 ${word.term}`} onClick={()=>update(d=>({...d,selected:d.selected.filter(x=>x.id!==word.id)}))}>×</button></div><label>语境释义<input maxLength={1000} value={word.meaning} placeholder="填写这句话中的意思" onChange={e=>update(d=>({...d,selected:d.selected.map(x=>x.id===word.id?{...x,meaning:e.target.value}:x)}))}/></label><blockquote lang="en">{word.context}</blockquote><details><summary>{word.section} · {word.page?('PDF '+word.page):word.locator??'位置待核对'} · 核对来源</summary><label>来源笔记（Vault 相对路径）<input value={word.sourceNote} maxLength={500} onChange={e=>update(d=>({...d,sourceNoteOverride:e.target.value,selected:d.selected.map(x=>({...x,sourceNote:e.target.value}))}))}/></label><label>PDF 页码（非 PDF 可留空）<input type="number" min={1} max={5000} value={word.page||''} onChange={e=>update(d=>({...d,selected:d.selected.map(x=>x.id===word.id?{...x,page:Number(e.target.value)}:x)}))}/></label></details></article>)}
    <div className="paper-actions"><button className="paper-primary" disabled={busy||(!draft.pending&&!draft.selected.length)||!!state.error} onClick={()=>void ingest(undefined,Boolean(draft.pending))}>{busy?'正在核对…':draft.pending?'重试原入库请求':'写入 Obsidian 词库'}</button><button disabled={!draft.selected.length||draft.selected.some(x=>!x.meaning.trim())} onClick={()=>download('学术阅读词卡.md',exportPaperVocabulary(draft.selected))}>导出五列表格</button><button disabled={!draft.selected.length||draft.selected.some(x=>!x.meaning.trim())} onClick={()=>void copyTextSafely(exportPaperVocabulary(draft.selected)).then(ok=>setMessage(ok?'五列表格已复制。':'复制不可用，请导出 Markdown。'))}>复制表格</button></div>
    {draft.pending&&<p>有待确认的入库请求。编辑托盘不会改变该请求；成功回执只清理未再修改的条目。</p>}
    {draft.receipt&&<div className="paper-ingest-readback" aria-label="收词状态"><dl><div><dt>词库文件</dt><dd>{paperVocabularyReceiptMessage(draft.receipt)}</dd></div><div><dt>本机材料</dt><dd>{draft.receipt.gatewayRecognized?'已识别收录词条':'尚未确认识别'}</dd></div><div><dt>网页资料</dt><dd>{!receiptEntries.length?'本次没有成功收录项':checkingVocabulary?'正在重新读取…':currentReadback?.status==='visible'?`已核对 ${currentReadback.matched} 个词条`:currentReadback?.status==='deferred'?'已读取，结束当前练习后更新':currentReadback?.status==='unavailable'?'暂时未能核对，可稍后重试':`等待${services.accountLibraryId?'账号同步与':''}资料刷新`}</dd></div></dl><p>收词不会产生练习成绩；学习日期按现有计划与额度安排。</p>{services.refreshVocabulary&&<button type="button" disabled={checkingVocabulary||!receiptEntries.length} onClick={()=>void refreshVocabulary(receiptEntries,draft.receipt!)}>{checkingVocabulary?'正在核对…':'重新核对网页词条'}</button>}</div>}
    <p className="paper-status" role="status">{message}</p>{!!draft.ingestedVocabulary?.length&&<p>本次已入库 {draft.ingestedVocabulary.length} 词，会随阅读笔记一起保存。</p>}{draft.receipt&&<details><summary>最近一次入库回执</summary><p>{draft.receipt.results.map(r=>`${r.status}: ${r.id}`).join('；')}</p><p>网关识别：{draft.receipt.gatewayRecognized?'已确认':'未确认'}。网站同步与复习排期需另外核对。</p></details>}
   </section>
  </section>} board={<aside className="paper-board">{paper.figures&&paper.figures.length>0&&<nav ref={figureNavigation} className="paper-figure-references" aria-label="论文图表">{paper.figures.map(f=><button key={f.assetId} data-figure-id={f.assetId} type="button" onClick={event=>openFigure(f.assetId,event.currentTarget)}>{f.label}</button>)}</nav>}{figure&&<PaperFigurePanel key={figure.assetId} figure={figure} origin={paper.origin} services={services} onClose={closeFigure}/>}<h2>主线重构</h2><label className="paper-label">整理模板<select aria-label="论文主线模板" value={template.id} onChange={event=>{controller.current?.abort();setAiBusy(false);setAiText('');setPrompt('');update(d=>setPaperTemplate(d,event.target.value));}}>{PAPER_SLOT_TEMPLATES.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><p>{template.description} 切换模板会保留各自已写内容，不自动替你填写。</p>{currentPaperSlots(draft).map((slot,i)=><label className="paper-label" key={template.id+slot.key}><span><b>0{i+1}</b> {slot.label}</span><textarea aria-label={slot.label} maxLength={3000} value={slot.value} onChange={e=>update(d=>setPaperSlot(d,slot.key,e.target.value))}/></label>)}{template.id==='empirical'&&Object.values(paper.fiveSlots??{}).some(Boolean)&&<details><summary>核对示例主线（仅参考）</summary>{Object.entries(paper.fiveSlots??{}).map(([k,v])=><p key={k}><strong>{PAPER_SLOTS[k as PaperSlot]}：</strong>{v}</p>)}</details>}
  <section className="paper-reviewer"><h2>AI 审稿人</h2>{reviewScopeNotice&&<p role="status">{reviewScopeNotice}</p>}<p>每次只围绕当前微段与你写下的主线追问。</p><div className="paper-chips">{paperReviewerActions(template.id).map(action=><button key={action} disabled={aiBusy} onClick={()=>void reviewer(action)}>{action}</button>)}</div>{aiBusy&&<button onClick={()=>{controller.current?.abort();setAiBusy(false);}}>停止回答</button>}{aiText&&<div className="paper-ai-answer"><strong>AI 参考 · 请回原文核对</strong><p>{aiText}</p></div>}{prompt&&<details><summary>本次提问内容</summary><pre>{prompt}</pre><button onClick={()=>void copyTextSafely(prompt).then(ok=>setMessage(ok?'审稿问题已复制。':'复制不可用，可选择上方文字复制。'))}>复制审稿问题</button></details>}</section></aside>}/>
  <CandidateLauncher source={{kind:'paper',key:paper.paperId,version:paper.origin?.version,versionKind:paper.origin?'paper-origin':'visible-snapshot',title:paper.title,fragments:paper.sections.flatMap(s=>s.paragraphs.map(p=>({id:p.id,label:`${s.title} · ${p.pageNumber?`第 ${p.pageNumber} 页`:p.id}`,text:p.rawEn,...(p.pageNumber?{page:p.pageNumber}:{})})))}} seeds={paperRetestSeeds(Object.entries(draft.selfcheck).filter(([,value])=>value==='还说不清').map(([key])=>key))} defaultFragmentId={paragraph.id} scope={JSON.stringify([services.owner,services.library])} isCurrent={services.isCurrent} registerGuard={registerStudyNavigationGuard} download={(name,text)=>download(name,text,'application/json')} label="从“还说不清”的项目准备复测候选"/>
  <PaperNoteSavePanel services={services} paper={paper} session={session} draft={draft}/><footer className="paper-footer"><div className="paper-actions"><button onClick={()=>{setSelection(null);setHidden(true);setActivePanel(1);setTimer(Date.now()+60000);}}>开读 1 分钟检索</button><button onClick={()=>{setSelection(null);setHidden(true);setActivePanel(1);setTimer(Date.now()+300000);}}>会末 5 分钟重构</button>{timer!==null&&<span role="timer">{remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'计时结束，请核对原文。'}</span>}<button onClick={()=>download('论文精读草稿.json',JSON.stringify({paper,draft},null,2),'application/json')}>导出完整草稿</button><button onClick={()=>{try{download('论文精读笔记.md',readingNoteMarkdown(paper,draft));}catch(error){setMessage(`${error instanceof Error?error.message:String(error)} 可先导出完整草稿保留所有输入。`);}}}>导出阅读笔记</button></div>
  <details><summary>主线自检（自评草稿）</summary>{paperSelfcheckLabels(template.id).map(k=><label className="paper-label" key={k}>{k}<select value={draft.selfcheck[k]??''} onChange={e=>update(d=>({...d,selfcheck:{...d.selfcheck,[k]:e.target.value}}))}><option value="">尚未自检</option><option>还说不清</option><option>有提示可解释</option><option>能闭卷解释，待复测</option></select></label>)}</details>
  {paper.paperId==='alexnet-2012'&&<a href="https://proceedings.neurips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf" target="_blank" rel="noreferrer">核对 AlexNet 原始论文 · §3.1 / 图 1 / 表 2</a>}</footer>
 </div>;
}
export function PaperWorkshop({services,initialPaper=DEMO_PAPER_ALEXNET,restoreLast=true}:{services:PaperServices;initialPaper?:PaperStudyData;restoreLast?:boolean}){
 const manager=useRef<HTMLDetailsElement>(null);
 const [paper,setPaper]=useState(initialPaper),[loaded,setLoaded]=useState<{session:PaperDraftSession;paper:PaperStudyData}|null>(null),[materials,setMaterials]=useState<PaperMaterial[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;void loadPaperMaterials(services.owner,services.library).then(items=>{if(active){setMaterials(items);if(restoreLast&&items[0])setPaper(items[0].paper);}}).catch(error=>{if(active)setError(String(error));});return()=>{active=false;};},[services.owner,services.library,restoreLast]);
 useEffect(()=>{let active=true;void openPaperDraft(services.owner,services.library,paper).then(s=>{if(active)setLoaded({session:s,paper});}).catch(error=>{if(active)setError(String(error));});return()=>{active=false;};},[services.owner,services.library,paper]);
 async function addMaterial(next:PaperStudyData){const material=await savePaperMaterial(services.owner,services.library,next);setMaterials(items=>[material,...items.filter(x=>x.fingerprint!==material.fingerprint)]);setPaper(material.paper);setError('');if(manager.current){manager.current.open=false;manager.current.scrollIntoView({block:'start'});}}
 return <><details ref={manager} className="paper-material-manager"><summary>更换论文 / 上传材料</summary><PaperSourcesPanel services={services} onImport={addMaterial}/><div className="paper-import"><button onClick={()=>setPaper(DEMO_PAPER_ALEXNET)}>原创合成示例</button>{materials.length>0&&<select aria-label="已保存的论文材料" value={materials.find(x=>x.paper===paper)?.fingerprint??''} onChange={e=>{const chosen=materials.find(x=>x.fingerprint===e.target.value);if(chosen){setPaper(chosen.paper);if(manager.current){manager.current.open=false;manager.current.scrollIntoView({block:'start'});}}}}><option value="">选择已保存材料</option>{materials.map(m=><option key={m.fingerprint} value={m.fingerprint}>{DISCIPLINES[m.paper.disciplineId as keyof typeof DISCIPLINES]?.label??'待分类'} · {m.paper.title}</option>)}</select>}<button onClick={()=>download('论文材料模板.json',JSON.stringify(DEMO_PAPER_ALEXNET,null,2),'application/json')}>下载材料模板</button></div></details>{error&&<p role="alert">{error}</p>}{loaded?.paper===paper?<PaperEditor key={loaded.session.kind} paper={paper} session={loaded.session} services={services}/>:<p>正在切换论文草稿…</p>}</>;
}
export function PaperWorkshopLauncher({services}:{services:PaperServices}){const [open,setOpen]=useState(false),dialog=useRef<HTMLDialogElement>(null);const managed=useManagedDialog(dialog,open,()=>setOpen(false));return <><button className="paper-launch" onClick={event=>{const menu=event.currentTarget.closest('details');menu?.removeAttribute('open');menu?.querySelector('summary')?.focus();setOpen(true);}}>论文精读工坊</button>{open&&createPortal(<div className="study-app study-modal-host" style={{display:'contents'}}><dialog ref={dialog} className="paper-dialog" aria-label="论文精读工坊" onClose={managed.onNativeClose} onCancel={event=>{event.preventDefault();managed.close();}}><button className="paper-close" onClick={managed.close} aria-label="关闭论文精读工坊">关闭工坊 ×</button><PaperWorkshop key={JSON.stringify([services.owner,services.library])} services={services}/></dialog></div>,document.body)}</>;}
export const PaperPlugin:StudyPlugin<{paper?:PaperStudyData}>= {id:'@zhixue/plugin-paper',name:'论文精读',description:'微段选词、因果主线与审稿追问；不自动产生学习评分。',renderUI:({data,context})=>{const paper=parsePaperStudyData(data.paper??data);return context?.paperServices?<PaperWorkshop services={context.paperServices} initialPaper={paper} restoreLast={false}/>:<p>请从论文精读工坊入口打开材料，以保留独立草稿与资料库绑定。</p>;}};
