// Actual React components with synthetic scoring/transport adapters and real browser IndexedDB.
// Default: locked project React via Vite in CI. Offline URL is local diagnostic mode only (reported explicitly).
import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';import {createRequire} from 'node:module';import {fixture,replacements} from './causal-fixture.mjs';
const require=createRequire(import.meta.url);
const {chromium}=process.env.CAUSAL_PLAYWRIGHT_MODULE?require(process.env.CAUSAL_PLAYWRIGHT_MODULE):createRequire(resolve(process.env.UX_BROWSER_DRIVER,'package.json'))('playwright');
const origin=process.env.CAUSAL_OFFLINE_URL||'http://127.0.0.1:4186';if(new URL(origin).hostname!=='127.0.0.1')throw Error('Only isolated loopback fixtures are permitted');
const evidence=resolve(process.env.UX_EVIDENCE||'scratch/ci-evidence/causal');await mkdir(evidence,{recursive:true});let server,browser,failure=null;const results=[];
if(!process.env.CAUSAL_OFFLINE_URL){
 const {createServer}=await import('vite'),{default:react}=await import('@vitejs/plugin-react');const root=process.cwd(),index=resolve('scratch/ci-causal/index.html');await mkdir(resolve('scratch/ci-causal'),{recursive:true});await writeFile(resolve('scratch/ci-causal/entry.tsx'),fixture);await writeFile(index,'<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="/scratch/ci-causal/entry.tsx"></script></html>');
 const doubles={name:'explicit-causal-service-doubles',enforce:'pre',resolveId(source,importer){let id=source.startsWith('/app/')?source.slice(1):source.startsWith('.')&&importer?resolve(importer.split('?')[0],'..',source).slice(root.length+1):source;for(const key of Object.keys(replacements))if([key,key.replace(/\.(?:tsx?|mjs)$/,''),key.replace(/\/index\.ts$/,'')].includes(id))return '\0causal-double:'+key;},load(id){if(id.startsWith('\0causal-double:'))return replacements[id.slice(15)];}};
 server=await createServer({configFile:false,root,plugins:[doubles,react()],server:{host:'127.0.0.1',port:4186,strictPort:true},logLevel:'error'});await server.listen();
}
const url=origin+(process.env.CAUSAL_OFFLINE_URL?'/':'/scratch/ci-causal/index.html');
const settle=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
async function mode(page,name){await page.evaluate(name=>window.__openMode(name),name);await settle(page);}
try{
 browser=await chromium.launch({headless:true,...(process.env.CAUSAL_CHROMIUM?{executablePath:process.env.CAUSAL_CHROMIUM}:{}),args:['--no-sandbox']});
 for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
  const context=await browser.newContext({viewport});context.setDefaultTimeout(10000);const errors=[];let allow=true;context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>allow?d.accept():d.dismiss());});
  await context.route('**/*',route=>new URL(route.request().url()).origin===origin&&!new URL(route.request().url()).pathname.startsWith('/api/')?route.continue():route.abort('blockedbyclient'));
  const page=await context.newPage();await page.goto(url);await page.locator('[data-question="A"]').waitFor();const runtime=await page.evaluate(()=>window.__reactVersion);const pass=label=>results.push({viewport:viewport.width,case:label,react:runtime,passed:true});
  await mode(page,'load');await page.getByRole('button',{name:'重试',exact:true}).click();await page.locator('[data-question="A"]').waitFor();assert.equal(await page.getByText('模拟读取失败',{exact:true}).count(),0);pass('load failure then success exits error state');
  await mode(page,'normal');await page.getByRole('button',{name:'模拟答错',exact:true}).click();await page.getByRole('button',{name:'重排复习',exact:true}).click();await page.getByRole('button',{name:'正在准备原题复习…',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'正在准备原题复习…',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'下次再考',exact:true}).click();await page.locator('[data-question="B"]').waitFor();await page.getByRole('textbox',{name:'隔离作答',exact:true}).fill('B needs to stay');await page.evaluate(()=>window.__causal.resolve({item:{itemId:'variant-A',questionType:'quiz',prompt:'late-A'}}));await settle(page);assert.equal(await page.getByRole('textbox',{name:'隔离作答',exact:true}).inputValue(),'B needs to stay');await page.getByRole('button',{name:'模拟答对',exact:true}).click();await page.getByRole('heading',{name:'隔离会话结束'}).waitFor();assert.deepEqual(await page.evaluate(()=>window.__causal.records),['A','B']);assert.equal(await page.evaluate(()=>window.__causal.variants),1);pass('late variant cannot replace B, duplicate request disabled, no queue omission');
  await mode(page,'normal');await page.getByRole('button',{name:'模拟答错'}).click();await page.getByRole('button',{name:'重排复习',exact:true}).click();await page.getByRole('button',{name:'结束复习',exact:true}).click();await page.evaluate(()=>window.__causal.reject(Error('late')));await settle(page);assert.equal(await page.locator('[data-view="done"]').count(),1);pass('ending invalidates a late failed variant');
  await mode(page,'calc');await page.getByRole('button',{name:'模拟计算提交'}).click();await page.getByRole('button',{name:'模拟继续'}).waitFor();assert.equal(await page.evaluate(()=>window.__causal.done),0);await page.getByRole('button',{name:'模拟继续'}).click();assert.equal(await page.evaluate(()=>window.__causal.records.length),1);pass('calculation persists once and waits for explicit continue');
  await mode(page,'tutor');const tutor=page.getByRole('textbox',{name:'向 AI 导师追问'});await tutor.fill('中文问题');await tutor.dispatchEvent('compositionstart');await tutor.dispatchEvent('keydown',{key:'Enter',isComposing:true,keyCode:229});await tutor.dispatchEvent('compositionend');assert.equal(await page.evaluate(()=>window.__causal.tutor),0);await tutor.press('Enter');await page.waitForFunction(()=>window.__causal.tutor===1);pass('IME selection Enter does not send, final Enter sends');
  await mode(page,'code');assert.equal(await page.locator('.study-code-prompt p').textContent(),'如果 x < 0，返回 -1；如果 x > 0，返回 1。\nvector<int>\n<img src=x onerror=alert(1)>');assert.equal(await page.locator('main img').count(),0);pass('code conditions and literal markup are not deleted or executed');
  await mode(page,'trial');await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){if(this.name==='A.md')return new Promise(resolve=>{window.__releaseFile=()=>resolve(new TextEncoder().encode('Q: 迟到文件 A\nA: 文件 A 参考答案').buffer);});return original.call(this);};});await page.locator('input[type=file][multiple]').setInputFiles({name:'A.md',mimeType:'text/markdown',buffer:Buffer.from('Q: A\nA: answer')});await page.waitForFunction(()=>typeof window.__releaseFile==='function');await page.getByRole('button',{name:'打开材料 B'}).click();await page.getByRole('heading',{name:'已保存材料 B'}).waitFor();await page.evaluate(()=>window.__releaseFile());await settle(page);assert.equal(await page.getByRole('heading',{name:'已保存材料 B'}).count(),1);await page.getByRole('textbox',{name:'先写下你的理解'}).fill('保留 B 的输入');allow=false;await page.getByRole('button',{name:'前往设置'}).click();assert.equal(await page.getByRole('textbox',{name:'先写下你的理解'}).inputValue(),'保留 B 的输入');allow=true;await page.getByRole('button',{name:'前往设置'}).click();await page.getByRole('heading',{name:'隔离设置页'}).waitFor();pass('saved B supersedes pending file A; cancelled navigation preserves input');
  const backup=await page.evaluate(()=>window.__backupRoundtrip());assert.deepEqual(backup,{count:1,secretExcluded:true,foreignRejected:true});pass('real IndexedDB material export, restore, idempotency and account boundary');
  await page.screenshot({path:resolve(evidence,`causal-${viewport.width}.png`),fullPage:true});assert.deepEqual(errors,[]);await context.close();
 }
 assert.equal(results.length,16);
}catch(error){failure=String(error.stack||error);throw error;}
finally{const report={sha:process.env.GITHUB_SHA||null,expected:16,passed:results.length,complete:!failure&&results.length===16,mode:process.env.CAUSAL_OFFLINE_URL?'offline-runtime-not-project-lock':'project-locked-runtime',failure,results};await writeFile(resolve(evidence,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser?.close();await server?.close();}
