// Browser acceptance for the psychology-driven UX remedies.
// Real React components, synthetic content only; all external requests are blocked.
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
const {chromium}=createRequire(resolve(process.env.UX_BROWSER_DRIVER,'package.json'))('playwright');
const root=resolve('scratch/ci-remedies'),evidence=resolve(process.env.UX_EVIDENCE||'scratch/ci-evidence/remedies');
await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});
await writeFile(resolve(root,'index.html'),'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module" src="/entry.tsx"></script></body></html>');
await writeFile(resolve(root,'entry.tsx'),String.raw`
import React,{useRef,useState} from 'react';import {createRoot} from 'react-dom/client';
import {LearningLibrary} from '../../app/learning-library';
import {NoteTrial} from '../../app/note-trial';
import {StudyItemSource} from '../../app/study-item-source';
import {GeneratedPlanStart} from '../../app/generated-plan-start';
import {PaperWorkspacePanels} from '../../app/paper-workspace-panels';
import {PaperWorkshopLauncher} from '../../app/paper-workshop-launcher';
import {PAPER_SLOT_TEMPLATES,currentPaperSlots,paperOutlineMarkdown,paperTemplate,setPaperSlot,setPaperTemplate} from '../../app/paper-slot-templates';
import {emptyPaperDraft} from '../../app/paper-study';import {ReviewContext} from '../../app/review-context';
import '../../app/globals.css';import '../../app/c-study.css';import '../../app/study-overview.css';import '../../app/plugins/paper.css';
document.documentElement.classList.toggle('dark',location.search.includes('theme=dark'));
const probe={generates:0,starts:0,resolve:null as null|((mode:'match'|'other')=>void)};Object.assign(window,{__remediesProbe:probe});
const subjects=[
 ...Array.from({length:3},(_,i)=>({id:'lang-'+i,name:'语言课程 '+(i+1),pluginType:'recall',disciplineId:'language',items:[{}]})),
 ...Array.from({length:3},(_,i)=>({id:'code-'+i,name:'计算课程 '+(i+1),pluginType:'recall',disciplineId:'computing',items:[{}]})),
 ...Array.from({length:2},(_,i)=>({id:'math-'+i,name:'数学课程 '+(i+1),pluginType:'recall',disciplineId:'math',items:[{}]})),
 ...Array.from({length:2},(_,i)=>({id:'course-'+i,name:'专业课程 '+(i+1),pluginType:'recall',disciplineId:'courses',items:[{}]})),
 ...Array.from({length:3},(_,i)=>({id:'other-'+i,name:'其他课程 '+(i+1),pluginType:'recall',disciplineId:'other',items:[{}]})),
];
function StartProbe(){const [hash,setHash]=useState<string|undefined>(),[disabled,setDisabled]=useState(false),[scope,setScope]=useState('scope-a');const resolver=useRef<((mode:'match'|'other')=>void)|null>(null);
 const generate=()=>{probe.generates++;return new Promise<string>(resolve=>{resolver.current=mode=>{setHash(mode==='match'?'plan-new':'plan-other');resolve('plan-new');};probe.resolve=mode=>resolver.current?.(mode);});};
 return <section aria-label="生成并开始验证" data-starts={probe.starts} data-generates={probe.generates}><GeneratedPlanStart key={scope} scope={scope} hash={hash} visible disabled={disabled} generate={generate} onStart={()=>{probe.starts++;document.body.dataset.started=String(probe.starts);}}/><button onClick={()=>probe.resolve?.('match')}>完成生成</button><button onClick={()=>probe.resolve?.('other')}>完成为其他计划</button><button onClick={()=>setDisabled(true)}>禁用入口</button><button onClick={()=>setScope('scope-b')}>切换范围</button></section>;}
function PaperProbe(){const [active,setActive]=useState<0|1>(0),[draft,setDraft]=useState(emptyPaperDraft()),[reading,setReading]=useState(''),[figure,setFigure]=useState(false),[exported,setExported]=useState('');const template=paperTemplate(draft.slotTemplate);
 return <section aria-label="论文响应式验证"><PaperWorkspacePanels active={active} onActiveChange={setActive} reading={<section><h2>文献阅读</h2><label>阅读批注<textarea value={reading} onChange={e=>setReading(e.target.value)}/></label><button onClick={()=>setFigure(value=>!value)}>切换图表</button>{figure&&<p>图表仍在当前阅读状态</p>}</section>} board={<section><h2>主线填答</h2><label>整理模板<select aria-label="测试论文主线模板" value={template.id} onChange={e=>setDraft(value=>setPaperTemplate(value,e.target.value))}>{PAPER_SLOT_TEMPLATES.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>{currentPaperSlots(draft).map(field=><label key={template.id+field.key}>{field.label}<textarea aria-label={'模板字段 '+field.label} value={field.value} onChange={e=>setDraft(value=>setPaperSlot(value,field.key,e.target.value))}/></label>)}<button onClick={()=>setExported(paperOutlineMarkdown(draft))}>导出主线</button><pre aria-label="主线导出结果">{exported}</pre></section>}/></section>;}
function App(){const [chosen,setChosen]=useState(''),[owner,setOwner]=useState('remedies-owner-a');const library=owner+'-library',featured=location.search.includes('featured=1');return <main className="study-app" data-page="today" data-chosen={chosen} data-owner={owner}><div className="workspace"><h1>心理阻抗修复 · 隔离浏览器验收</h1>
 {featured&&<NoteTrial featured owner={owner} library={library} onConnect={()=>setChosen('sources')}/>}
 <section><h2>本页笔记试学与出处</h2><button onClick={()=>setOwner(value=>value.endsWith('-a')?'remedies-owner-b':'remedies-owner-a')}>切换折叠测试学习库</button><LearningLibrary showTrial={!featured} subjects={subjects} owner={owner} library={library} onChoose={setChosen} onSources={()=>setChosen('sources')} paper={<PaperWorkshopLauncher services={{owner,library}}/>}/><StudyItemSource item={{sourceNote:'课程/讲义.md#卷积公式'}} source={{title:'测试课程',scope:'当前题目'}} canOpenLocal={false} getObsidianUri={()=>''} preferenceScope="remedies-owner/remedies-library"/></section>
 <PaperProbe/><StartProbe/><section aria-label="复习说明验证"><ReviewContext/><ReviewContext recorded due="2026-09-20T00:00:00Z"/><ReviewContext temporary due="2026-09-20T00:00:00Z"/></section>
 </div></main>;}createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
`);
const origin='http://127.0.0.1:4183';
const server=await createServer({configFile:false,root,plugins:[react()],server:{host:'127.0.0.1',port:4183,strictPort:true,fs:{allow:[process.cwd()]}},logLevel:'error'});
let browser,failure=null;const results=[];
async function settle(page){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function open(viewport,theme,denyStorage=false){const context=await browser.newContext({viewport,colorScheme:theme});context.setDefaultTimeout(20000);const errors=[],outside=[];context.on('page',page=>page.on('pageerror',error=>errors.push(error.message)));await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin){outside.push(url.href);return route.abort('blockedbyclient');}if(url.pathname.startsWith('/api/'))return route.abort('blockedbyclient');return route.continue();});await context.addInitScript(({origin,denyStorage})=>{if(location.origin!==origin)return;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new DOMException('denied','NotAllowedError'))}});if(denyStorage)Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('blocked','SecurityError');}});},{origin,denyStorage});const page=await context.newPage();await page.goto(origin+'/?theme='+theme);await page.getByRole('heading',{name:'心理阻抗修复 · 隔离浏览器验收'}).waitFor();await settle(page);return{context,page,errors,outside};}
function common(viewport,theme){return{viewport:viewport.width,theme};}
async function assertClean(page,errors,outside){assert.deepEqual(errors,[]);assert.deepEqual(outside,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}
try{
 await server.listen();browser=await chromium.launch({headless:true});
 for(const viewport of [{width:1440,height:900},{width:390,height:844}])for(const theme of ['light','dark']){
  {
   const {context,page,errors,outside}=await open(viewport,theme);await page.goto(origin+'/?theme='+theme+'&featured=1');const trial=page.locator('.note-trial');await trial.getByText('用自己的笔记，开始第一轮练习',{exact:true}).waitFor();assert.equal(await trial.count(),1);const input=trial.locator('input[type=file][multiple]');assert.equal(await input.isVisible(),true);assert.equal(await input.evaluate(el=>el.getBoundingClientRect().bottom<innerHeight),true);await page.screenshot({path:resolve(evidence,'featured-trial-'+theme+'-'+viewport.width+'.png')});
   await input.setInputFiles({name:'bad.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await page.getByText('仅支持 .md、.markdown 和 .txt 文件。',{exact:true}).waitFor();
   await input.setInputFiles([{name:'甲.md',mimeType:'text/markdown',buffer:Buffer.from('# 甲\nQ: 甲问题？\nA: <img src=x onerror=alert(1)> 甲答案')},{name:'乙.txt',mimeType:'text/plain',buffer:Buffer.from('问：乙问题？\n答：乙答案')}]);
   await page.getByRole('heading',{name:'甲问题？'}).waitFor();await page.getByRole('textbox',{name:'先写下你的理解'}).fill('我的回答');await page.getByRole('button',{name:'查看原文并自评'}).click();assert.equal(await trial.locator('blockquote img').count(),0);assert.match(await trial.locator('blockquote').innerText(),/<img/);await page.getByRole('button',{name:'仍不熟悉，标记再练'}).click();await page.getByRole('heading',{name:'乙问题？'}).waitFor();await page.getByRole('button',{name:'查看原文并自评'}).click();await page.getByRole('button',{name:'已能回忆，完成本轮'}).click();await page.getByRole('heading',{name:'已完成 2 道笔记试学'}).waitFor();await page.getByRole('button',{name:'只练标记的 1 道题',exact:true}).click();await page.getByRole('heading',{name:'甲问题？'}).waitFor();assert.match(await trial.innerText(),/困难题再练 · 第 1 \/ 1 题/);await page.getByRole('button',{name:'查看原文并自评'}).click();await page.getByRole('button',{name:'已能回忆，完成本轮'}).click();await page.getByRole('heading',{name:'已完成 1 道困难题再练'}).waitFor();
   await trial.getByText('保存到本机待学材料',{exact:true}).click();await trial.getByRole('textbox',{name:'学科名称',exact:true}).fill('测试课程');await trial.getByRole('textbox',{name:'材料名称',exact:true}).fill('我的两道题');await trial.getByRole('button',{name:'确认保存材料',exact:true}).click();await trial.getByText('已保存。可在学科列表下方的',{exact:false}).waitFor();await trial.getByRole('button',{name:'确认保存材料',exact:true}).click();await page.getByRole('heading',{name:'本机待学材料 · 1 份',exact:true}).waitFor();
   await page.reload();await page.getByRole('searchbox',{name:'查找学科、课程或本机材料',exact:true}).fill('测试课程');await page.getByRole('heading',{name:'本机待学材料 · 1 份',exact:true}).waitFor();assert.equal(await page.getByText('没有匹配的学科或本机材料。可以调整关键词，或添加学习资料。',{exact:true}).count(),0);await page.getByRole('button',{name:'我的两道题 · 2 题 · 重新练习',exact:true}).click();await page.getByRole('heading',{name:'甲问题？'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'先写下你的理解'}).inputValue(),'');assert.equal(await page.locator('.note-trial blockquote').count(),0);
   const counts=await page.evaluate(()=>new Promise((resolve,reject)=>{const open=indexedDB.open('zhixue-local-study-v1');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction(['study-events-v3','task-events-v1'],'readonly'),a=tx.objectStore('study-events-v3').count(),b=tx.objectStore('task-events-v1').count();tx.oncomplete=()=>{db.close();resolve([a.result,b.result]);};tx.onerror=()=>{db.close();reject(tx.error);};};}));assert.deepEqual(counts,[0,0]);
   const source=page.locator('.study-source-detail');await source.locator('details summary').click();const vault=page.getByRole('textbox',{name:'本机 Obsidian 库名'});assert.equal(await vault.getAttribute('placeholder'),'例如：MyVault');assert.match(await source.innerText(),/库切换器/);await vault.fill('学习 库');const href=await source.getByRole('link',{name:'在本机 Obsidian 中打开所属笔记'}).getAttribute('href');assert.match(href,/^obsidian:\/\/open\?/);assert.equal(new URL(href).searchParams.get('file'),'课程/讲义.md#卷积公式');await page.getByRole('button',{name:'复制笔记路径与小节'}).click();await page.getByText('复制不可用，请选中下方路径手动复制。',{exact:true}).waitFor();await assertClean(page,errors,outside);results.push({...common(viewport,theme),case:'two-file trial, explicit deduplicated material save/reload, zero grades and safe Obsidian guidance',passed:true});await context.close();
  }
  {
   const {context,page,errors,outside}=await open(viewport,theme);const search=page.getByRole('searchbox',{name:'查找学科、课程或本机材料'});await page.getByRole('button',{name:/其他与待分类 · 3/}).waitFor();assert.equal(await page.getByRole('button',{name:/其他课程 3/}).isVisible(),false);await search.fill('其他课程 3');await page.getByRole('button',{name:/其他课程 3/}).waitFor();await search.fill('');assert.equal(await page.getByRole('button',{name:/其他课程 3/}).isVisible(),false);await page.getByRole('button',{name:/其他与待分类 · 3/}).click();await page.getByRole('button',{name:/其他课程 3/}).waitFor();await page.getByRole('button',{name:'切换折叠测试学习库'}).click();await page.locator('main[data-owner="remedies-owner-b"]').waitFor();assert.equal(await page.getByRole('button',{name:/其他课程 3/}).isVisible(),false);await page.getByRole('button',{name:'切换折叠测试学习库'}).click();await page.locator('main[data-owner="remedies-owner-a"]').waitFor();await page.getByRole('button',{name:/其他课程 3/}).waitFor();await page.getByRole('button',{name:/其他与待分类/}).filter({hasText:'−'}).click();await page.reload();await page.getByRole('heading',{name:'心理阻抗修复 · 隔离浏览器验收'}).waitFor();await settle(page);assert.equal(await page.getByRole('button',{name:/其他课程 3/}).isVisible(),false);await assertClean(page,errors,outside);results.push({...common(viewport,theme),case:'large-library fold, search restoration, owner/library isolation and persisted disclosure',passed:true});await context.close();
   const denied=await open(viewport,theme,true);await denied.page.locator('.library-group-toggle').filter({hasText:'计算机与人工智能'}).click();await denied.page.getByText('折叠状态仅在当前页面保留，学习内容与进度不受影响。',{exact:true}).waitFor();await assertClean(denied.page,denied.errors,denied.outside);await denied.context.close();
  }
  {
   const {context,page,errors,outside}=await open(viewport,theme);const narrow=viewport.width<=800;if(narrow)await page.getByRole('tab',{name:'文献阅读'}).waitFor();else assert.equal(await page.getByRole('tab').count(),0);await page.getByRole('textbox',{name:'阅读批注'}).fill('阅读状态');await page.getByRole('button',{name:'切换图表'}).click();if(narrow)await page.getByRole('tab',{name:'主线填答'}).click();const select=page.getByRole('combobox',{name:'测试论文主线模板'});await select.selectOption('empirical');await page.getByRole('textbox',{name:'模板字段 研究问题'}).fill('实验问题');await select.selectOption('theory');await page.getByRole('textbox',{name:'模板字段 核心论题'}).fill('理论论题');await select.selectOption('free');await page.getByRole('textbox',{name:'模板字段 它解决了什么'}).fill('自由问题');await select.selectOption('empirical');assert.equal(await page.getByRole('textbox',{name:'模板字段 研究问题'}).inputValue(),'实验问题');await page.getByRole('button',{name:'导出主线'}).click();const exported=await page.getByLabel('主线导出结果').innerText();assert.match(exported,/实验问题/);assert.match(exported,/理论论题/);assert.match(exported,/自由问题/);
   await page.setViewportSize(narrow?{width:1440,height:900}:{width:390,height:844});await settle(page);assert.equal(await page.getByLabel('阅读批注').inputValue(),'阅读状态');assert.equal(await page.getByText('图表仍在当前阅读状态',{exact:true}).count(),1);await page.setViewportSize(viewport);await settle(page);
   await page.getByRole('button',{name:'论文精读工坊',exact:true}).click();let dialog=page.getByRole('dialog',{name:'论文精读工坊'});await dialog.waitFor();if(narrow)await dialog.getByRole('tab',{name:'主线填答'}).click();let realTemplate=dialog.getByRole('combobox',{name:'论文主线模板'});await realTemplate.selectOption('empirical');await dialog.getByRole('textbox',{name:'研究问题'}).fill('真实实验草稿');await realTemplate.selectOption('theory');await dialog.getByRole('textbox',{name:'核心论题'}).fill('真实理论草稿');await dialog.getByRole('button',{name:'关闭论文精读工坊'}).click();await dialog.waitFor({state:'detached'});
   await page.getByRole('button',{name:'论文精读工坊',exact:true}).click();dialog=page.getByRole('dialog',{name:'论文精读工坊'});await dialog.waitFor();if(narrow)await dialog.getByRole('tab',{name:'主线填答'}).click();realTemplate=dialog.getByRole('combobox',{name:'论文主线模板'});assert.equal(await realTemplate.inputValue(),'theory');assert.equal(await dialog.getByRole('textbox',{name:'核心论题'}).inputValue(),'真实理论草稿');await dialog.getByRole('button',{name:'关闭论文精读工坊'}).click();await page.reload();await page.getByRole('heading',{name:'心理阻抗修复 · 隔离浏览器验收'}).waitFor();await page.getByRole('button',{name:'论文精读工坊',exact:true}).click();dialog=page.getByRole('dialog',{name:'论文精读工坊'});await dialog.waitFor();if(narrow)await dialog.getByRole('tab',{name:'主线填答'}).click();assert.equal(await dialog.getByRole('combobox',{name:'论文主线模板'}).inputValue(),'theory');assert.equal(await dialog.getByRole('textbox',{name:'核心论题'}).inputValue(),'真实理论草稿');const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'导出阅读笔记'}).click()]);const downloaded=await readFile(await download.path(),'utf8');assert.match(downloaded,/真实理论草稿/);assert.match(downloaded,/真实实验草稿/);await dialog.getByRole('button',{name:'关闭论文精读工坊'}).click();
   await assertClean(page,errors,outside);results.push({...common(viewport,theme),case:'paper tabs, resize, close/reopen/refresh and 5/4/3 template export retain drafts',passed:true});await context.close();
  }
  {
   let opened=await open(viewport,theme);let {page}=opened;const start=page.getByRole('button',{name:'开始今日练习'});await start.dblclick();await page.getByRole('button',{name:'完成生成'}).click();await page.waitForFunction(()=>document.body.dataset.started==='1');assert.deepEqual(await page.evaluate(()=>({generates:window.__remediesProbe.generates,starts:window.__remediesProbe.starts})),{generates:1,starts:1});await assertClean(page,opened.errors,opened.outside);await opened.context.close();
   opened=await open(viewport,theme);page=opened.page;await page.getByRole('button',{name:'开始今日练习'}).click();await page.getByRole('button',{name:'禁用入口'}).click();await page.getByRole('button',{name:'完成生成'}).click();await page.getByText('页面或学习资料已经变化，请重新开始。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__remediesProbe.starts),0);await opened.context.close();
   opened=await open(viewport,theme);page=opened.page;await page.getByRole('button',{name:'开始今日练习'}).click();await page.getByRole('button',{name:'切换范围'}).click();await page.getByRole('button',{name:'完成生成'}).click();await settle(page);assert.equal(await page.evaluate(()=>window.__remediesProbe.starts),0);assert.match(await page.locator('[aria-label="复习说明验证"]').innerText(),/新排期待核对/);assert.doesNotMatch(await page.locator('[aria-label="复习说明验证"]').innerText(),/保留率|4 天后/);await assertClean(page,opened.errors,opened.outside);await page.screenshot({path:resolve(evidence,'remedies-'+theme+'-'+viewport.width+'.png'),fullPage:true});results.push({...common(viewport,theme),case:'one generated start only; disabled/scope changes cancel and review copy stays evidence-bound',passed:true});await opened.context.close();
  }
 }
 assert.equal(results.length,16,'All 16 remedies scenarios must execute');
}catch(error){failure=String(error.stack||error);throw error;}finally{const report={sha:process.env.GITHUB_SHA||null,expected:16,passed:results.length,complete:failure===null&&results.length===16,failure,results};await writeFile(resolve(evidence,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser?.close();await server.close();}
