import assert from 'node:assert/strict';import test from 'node:test';import {openD1} from './helpers/sqlite-d1.mjs';import {AccountStudyAiStore} from '../db/account-study-ai-store.ts';
const TRACE={operationKind:'plan',modelId:'deepseek-v4-flash',promptVersion:'plan-ai-json-v1',ruleVersion:'plan-ai-selection-v1'};
const begin=(store,scope,value)=>store.begin(scope,{...value,trace:TRACE});
test('unlimited daily usage bypasses daily budgets while preserving concurrency and explicit opt-in',async t=>{
 const {store,scope}=await setup(t);assert.equal((await store.getSettings(scope)).unlimitedDailyUsage,false);
 const base={enabled:true,dailyRequestLimit:1,dailyTokenLimit:100,maxOutputTokens:100,confirmCosts:true};
 await assert.rejects(store.configure(scope,{...base,expectedRevision:0,unlimitedDailyUsage:'yes',providerKey:'synthetic-test-key'}),/invalid/);
 await store.configure(scope,{...base,expectedRevision:0,unlimitedDailyUsage:true,providerKey:'synthetic-test-key'});
 for(let i=0;i<12;i++){const requestId=`unlimited-${i}`,inputHash=String(i).padStart(64,'a');assert.equal((await begin(store,scope,{requestId,day:'2026-09-08',inputHash,reservedTokens:2500})).status,'accepted');await store.complete(scope,requestId,inputHash,{ok:true},2500);}
 await begin(store,scope,{requestId:'unlimited-pending',day:'2026-09-08',inputHash:'b'.repeat(64)});
 await assert.rejects(begin(store,scope,{requestId:'unlimited-concurrent',day:'2026-09-08',inputHash:'c'.repeat(64)}),/concurrency/);
 await store.fail(scope,'unlimited-pending','b'.repeat(64),'synthetic-failure');
 assert.equal((await store.configure(scope,{...base,expectedRevision:1})).settings.unlimitedDailyUsage,true);
 assert.equal((await store.configure(scope,{...base,expectedRevision:2,unlimitedDailyUsage:false})).settings.unlimitedDailyUsage,false);
 await assert.rejects(begin(store,scope,{requestId:'limited-again',day:'2026-09-08',inputHash:'d'.repeat(64)}),/limit/);
});
async function setup(t){const {sqlite,binding}=await openD1();t.after(()=>sqlite.close());await binding.prepare('INSERT INTO learning_accounts(user_id) VALUES (?)').bind('user-a').run();await binding.prepare('INSERT INTO account_study_libraries(user_id,library_id) VALUES (?,?)').bind('user-a','library-a').run();return{store:new AccountStudyAiStore(binding,Buffer.alloc(32,5).toString('base64url')),binding,scope:{userId:'user-a',libraryId:'library-a'}};}
test('AI enable requires explicit cost confirmation, per-account key and budget bounds',async t=>{const {store,scope,binding}=await setup(t);await assert.rejects(store.configure(scope,{enabled:true,dailyRequestLimit:3,maxOutputTokens:500,expectedRevision:0,confirmCosts:false,providerKey:'deepseek-test-key'}),/confirmation/);await assert.rejects(store.configure(scope,{enabled:true,dailyRequestLimit:3,maxOutputTokens:500,expectedRevision:0,confirmCosts:true}),/key-required/);const result=await store.configure(scope,{enabled:true,dailyRequestLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});assert.equal(result.status,'accepted');assert.equal(result.settings.revision,1);assert.equal(result.settings.configured,true);assert.equal(await store.providerKey(scope),'deepseek-test-key');const row=await binding.prepare('SELECT credential_ciphertext FROM account_study_ai_settings WHERE user_id=?').bind('user-a').first();assert.doesNotMatch(row.credential_ciphertext,/deepseek-test-key/);});
test('AI reservations persist model prompt and validation-rule provenance',async t=>{const {store,scope,binding}=await setup(t);await store.configure(scope,{enabled:true,dailyRequestLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});await begin(store,scope,{requestId:'trace-request',day:'2026-09-01',inputHash:'f'.repeat(64)});const row=await binding.prepare('SELECT operation_kind,model_id,prompt_version,rule_version FROM account_study_ai_requests WHERE request_id=?').bind('trace-request').first();assert.deepEqual({...row},{operation_kind:'plan',model_id:'deepseek-v4-flash',prompt_version:'plan-ai-json-v1',rule_version:'plan-ai-selection-v1'});});
test('completed retry uses stored provenance when the current server trace is unavailable',async t=>{const {store,scope}=await setup(t);await store.configure(scope,{enabled:true,dailyRequestLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});const inputHash='9'.repeat(64);await begin(store,scope,{requestId:'trace-retry',day:'2026-09-01',inputHash});await store.complete(scope,'trace-retry',inputHash,{selectedUnitIds:[],trace:TRACE},10);const unavailable={...TRACE,modelId:''},retry=await store.begin(scope,{requestId:'trace-retry',day:'2026-09-01',inputHash,trace:unavailable});assert.equal(retry.status,'completed');await assert.rejects(store.begin(scope,{requestId:'new-without-trace',day:'2026-09-01',inputHash:'8'.repeat(64),trace:unavailable}),/model/);});
test('daily reservation is concurrent-safe and completed retry never calls provider twice',async t=>{const {store,scope}=await setup(t);await store.configure(scope,{enabled:true,dailyRequestLimit:2,concurrentLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});
  await begin(store,scope,{requestId:'request-0',day:'2026-09-01',inputHash:'0'.padStart(64,'a')});const requests=Array.from({length:4},(_,i)=>begin(store,scope,{requestId:`request-${i+1}`,day:'2026-09-01',inputHash:String(i+1).padStart(64,'a')}));const results=await Promise.allSettled(requests);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  await store.complete(scope,'request-0','0'.padStart(64,'a'),{selectedUnitIds:[]},15);const retry=await begin(store,scope,{requestId:'request-0',day:'2026-09-01',inputHash:'0'.padStart(64,'a')});assert.equal(retry.status,'completed');assert.deepEqual(retry.result,{selectedUnitIds:[]});
});
test('same request ID with changed content conflicts and accounts are isolated',async t=>{const {store,scope}=await setup(t);await store.configure(scope,{enabled:true,dailyRequestLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});await begin(store,scope,{requestId:'stable-request',day:'2026-09-01',inputHash:'a'.repeat(64)});await assert.rejects(begin(store,scope,{requestId:'stable-request',day:'2026-09-01',inputHash:'b'.repeat(64)}),/conflict/);assert.equal((await store.getSettings({userId:'user-b',libraryId:'library-a'}).catch(()=>null)),null);});
test('completed idempotency survives disable and failed requests never masquerade as pending',async t=>{
  const {store,scope}=await setup(t);await store.configure(scope,{enabled:true,dailyRequestLimit:3,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-test-key'});
  const hash='c'.repeat(64);await begin(store,scope,{requestId:'completed-request',day:'2026-09-01',inputHash:hash});await store.complete(scope,'completed-request',hash,{selectedUnitIds:['course:u1']},21);
  await store.configure(scope,{enabled:false,dailyRequestLimit:3,maxOutputTokens:300,expectedRevision:1,confirmCosts:false});
  const completed=await begin(store,scope,{requestId:'completed-request',day:'2026-09-01',inputHash:hash});assert.equal(completed.status,'completed');assert.deepEqual(completed.result,{selectedUnitIds:['course:u1']});
  await store.configure(scope,{enabled:true,dailyRequestLimit:3,maxOutputTokens:300,expectedRevision:2,confirmCosts:true});
  const failedHash='d'.repeat(64);await begin(store,scope,{requestId:'failed-request',day:'2026-09-01',inputHash:failedHash});await store.fail(scope,'failed-request',failedHash,'cloud-ai-provider-error');
  const failed=await begin(store,scope,{requestId:'failed-request',day:'2026-09-01',inputHash:failedHash});assert.equal(failed.status,'failed');assert.equal(failed.errorCode,'cloud-ai-provider-error');
});
test('concurrent settings CAS has one winner and same request ID converges',async t=>{const {store,scope}=await setup(t),settings=await Promise.all([store.configure(scope,{enabled:true,dailyRequestLimit:2,concurrentLimit:2,maxOutputTokens:300,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-key-one'}),store.configure(scope,{enabled:true,dailyRequestLimit:9,concurrentLimit:2,maxOutputTokens:900,expectedRevision:0,confirmCosts:true,providerKey:'deepseek-key-two'})]);assert.deepEqual(settings.map(result=>result.status).sort(),['accepted','stale']);const saved=await store.getSettings(scope);assert.ok([[2,300],[9,900]].some(([limit,tokens])=>saved.dailyRequestLimit===limit&&saved.maxOutputTokens===tokens));const hash='e'.repeat(64),requests=await Promise.all([begin(store,scope,{requestId:'same-concurrent-request',day:'2026-09-01',inputHash:hash}),begin(store,scope,{requestId:'same-concurrent-request',day:'2026-09-01',inputHash:hash})]);assert.deepEqual(requests.map(result=>result.status).sort(),['accepted','pending']);});
test('provider settings preserve encrypted keys and reject stale switches',async t=>{const {store,scope,binding}=await setup(t);const base={enabled:true,dailyRequestLimit:3,maxOutputTokens:500,confirmCosts:true};await store.configure(scope,{...base,expectedRevision:0,providerKey:'deepseek-test-key',provider:'deepseek',model:'ds-model'});await store.configure(scope,{...base,expectedRevision:1,providerKey:'openai-test-key',provider:'chatgpt',model:'oa-model',baseUrl:'https://api.openai.com/v1'});assert.equal(await store.providerKey(scope),'openai-test-key');const settings=await store.getSettings(scope);assert.equal(settings.providers.deepseek.configured,true);assert.equal(settings.model,'oa-model');assert.doesNotMatch(JSON.stringify(settings),/test-key|ciphertext|nonce/);assert.equal((await store.configure(scope,{...base,provider:'deepseek',expectedRevision:1})).status,'stale');await store.configure(scope,{...base,provider:'deepseek',expectedRevision:2});assert.equal(await store.providerKey(scope),'deepseek-test-key');assert.equal((await store.getSettings(scope)).model,'ds-model');const row=await binding.prepare('SELECT provider_configs FROM account_study_ai_settings').first();assert.doesNotMatch(row.provider_configs,/openai-test-key/);});
test('configuration change at reservation INSERT leaves no stale request or consumed slot',async t=>{
 const {store,scope,binding}=await setup(t),base={enabled:true,dailyRequestLimit:3,dailyTokenLimit:6000,maxOutputTokens:500,confirmCosts:true,providerKey:'synthetic-key-only'};
 await store.configure(scope,{...base,provider:'deepseek',model:'old-model',expectedRevision:0});const prepare=binding.prepare.bind(binding);let switched=false;
 binding.prepare=sql=>{const statement=prepare(sql);if(!sql.startsWith('INSERT INTO account_study_ai_requests'))return statement;return{bind:(...values)=>{const bound=statement.bind(...values);return{run:async()=>{if(!switched){switched=true;await store.configure(scope,{...base,provider:'chatgpt',model:'new-model',expectedRevision:1});}return bound.run();}};}};};
 await assert.rejects(store.begin(scope,{requestId:'at-insert-race',day:'2026-09-08',inputHash:'3'.repeat(64),expectedRevision:1,trace:{...TRACE,provider:'deepseek',modelId:'old-model'}}),/ai-settings-stale/);
 binding.prepare=prepare;assert.equal(await binding.prepare('SELECT count(*) AS n FROM account_study_ai_requests').first('n'),0);
 const result=await store.begin(scope,{requestId:'at-insert-race',day:'2026-09-08',inputHash:'4'.repeat(64),expectedRevision:2,trace:{...TRACE,provider:'chatgpt',modelId:'new-model'}});assert.equal(result.status,'accepted');assert.equal((await binding.prepare('SELECT provider_id,model_id FROM account_study_ai_requests').first()).provider_id,'chatgpt');
});
