import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {codeRunFailure} from '../src/domain/remediation/index.ts';
const source=ts.createSourceFile('code.tsx',readFileSync(new URL('../app/plugins/plugin-code.tsx',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
function action(name,bindings){let found;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(source)===name)found=n.initializer;ts.forEachChild(n,visit);}visit(source);assert.ok(found);const exports={};new Function(...Object.keys(bindings),'exports',ts.transpileModule(`exports.run=${found.getText(source)}`,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(...Object.values(bindings),exports);return exports.run;}
function fixture(extra={}){const state={},calls=[];const bindings={firstOutput:'',codeRunFailure,isReady:true,isTesting:false,codeState:'coding',data:{testCode:'assert x == 1'},assistance:{submit:()=>calls.push('submit')},runEpoch:{current:0},code:'x = 1',stdin:'custom',runPython:async(...args)=>{calls.push(args);return {output:'ok',assertionsPassed:2};},...Object.fromEntries(['IsTesting','Panel','ResultKind','Elapsed','TestOutput','TestOutputId','CodeState','FailedOnce','FirstCode','FirstOutput'].map(key=>['set'+key,value=>{state[key]=value;}])),...extra};return {state,calls,bindings,run:action('handleRunTests',bindings)};}
test('trial runs only learner code and never unlocks completion',async()=>{const f=fixture();await f.run('trial');assert.deepEqual(f.calls[0],['x = 1',true,'custom',undefined]);assert.equal(f.state.CodeState,undefined);assert.equal(f.state.ResultKind,'trial');});
test('official checks use provided assertions, not custom input, and unlock completion only on success',async()=>{const f=fixture();await f.run();assert.deepEqual(f.calls,['submit',['x = 1',true,'','assert x == 1']]);assert.equal(f.state.CodeState,'passed');});
test('missing assertions, overlapping runs and an already passed answer cannot rerun',async()=>{for(const patch of [{data:{testCode:' '}},{isTesting:true},{codeState:'passed'}]){const f=fixture(patch);await f.run();assert.deepEqual(f.calls,[]);assert.deepEqual(f.state,{});}});
test('cancellation and environment failure do not mark learner failure; attributed Python program errors do',async()=>{for(const name of ['AbortError','RuntimeError','PythonError']){const error=new Error('failure');error.name=name;if(name==='PythonError')error.executionPhase='program';const f=fixture({runPython:async()=>{throw error;}});await f.run();assert.equal(f.state.CodeState,undefined);assert.equal(f.state.FailedOnce,name==='PythonError'?true:undefined);assert.equal(f.state.IsTesting,false);}});
test('a disposed question ignores a late result',async()=>{let complete;const f=fixture({runPython:()=>new Promise(resolve=>complete=resolve)});const pending=f.run();f.bindings.runEpoch.current++;complete({output:'late'});await pending;assert.equal(f.state.CodeState,undefined);assert.notEqual(f.state.TestOutput,'late');});
test('continue cannot grade a coding or running answer, and preserves relearning after failure',()=>{for(const [codeState,isTesting,failedOnce,expected]of [['coding',false,false,null],['passed',true,false,null],['passed',false,false,'good'],['passed',false,true,'again'],['gave_up',false,false,'again']]){let grade=null;action('handleNext',{codeState,isTesting,failedOnce,onGrade:value=>grade=value})();assert.equal(grade,expected);}});
test('a successful program response without executed assertions is not a passing challenge',async()=>{const f=fixture({runPython:async()=>({output:'no errors'})});await f.run();assert.equal(f.state.CodeState,undefined);assert.equal(f.state.ResultKind,'test-error');assert.equal(f.state.FailedOnce,undefined);});
