import assert from 'node:assert/strict';
import test from 'node:test';
import {vocabularyInput,courseSubject} from './fixtures/task-plan-input.mjs';
import {withStudyEventCoreHash,SCHEDULER_VERSION} from '../app/study-event-v3.ts';
import {rebuildEventProgress} from '../app/review-projection.ts';
import {forecastLongTermReviews} from '../app/long-term-review-forecast.ts';
let api;try{api=await import('../app/long-term-editor-source.ts');}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;}
const hash='c'.repeat(64);
function input(){const value=vocabularyInput(0);value.catalog.subjects.push(courseSubject(0));value.catalog.practiceSources=[{itemKey:'practice:one',subjectId:'course',sourceHash:hash,title:'One',completionRule:'graded-practice'}];return value;}
async function attempt(id,date='2026-08-30T03:00:00.000Z',overrides={}){return withStudyEventCoreHash({schemaVersion:3,eventId:id,coreHash:'',occurredAt:date,domain:'python',eventType:'practice-attempt',item:{kind:'python',key:'practice:one'},attempt:{rating:'good',correct:true,stageBefore:2,stageAfter:3},scheduling:{reviewedAt:date,schedulerVersion:SCHEDULER_VERSION},...overrides});}
async function build(args){assert.equal(typeof api?.buildLongTermEditorSource,'function');return api.buildLongTermEditorSource(args);}
test('current source completion supplies one round with real replayed FSRS, history and immutable inputs',async()=>{
 const value=input(),event=await attempt('complete'),args={input:value,events:[event],sourceHashesByEventId:{complete:hash},stamp:'s',todayLocked:true},before=structuredClone(args);
 const result=await build(args),replay=await rebuildEventProgress([event]);assert.equal(result.inventory[0].completedRounds,1);assert.equal(result.inventory[0].blockedReason,undefined);assert.notEqual(result.inventory[0].mastered,true);assert.deepEqual(result.fsrsMap,replay.fsrsData);assert.deepEqual(result.history,[{itemId:'practice:one',sourceHash:hash,date:'2026-08-30',completedRounds:1}]);assert.deepEqual(result.subjects,value.catalog.subjects.map(({subjectId,name,priority})=>({subjectId,name,priority})));assert.equal(result.stamp,'s');assert.equal(result.todayLocked,true);assert.deepEqual(args,before);
});
test('old-version and unknown events never supply current FSRS or rounds',async()=>{for(const provenance of ['d'.repeat(64),undefined]){const result=await build({input:input(),events:[await attempt('old')],sourceHashesByEventId:provenance?{old:provenance}:{}});assert.deepEqual(result.fsrsMap,{});assert.equal(result.inventory[0].completedRounds,0);assert.deepEqual(result.history,[]);}});
test('due-only source preserves actual horizon with explicit conditional parameters and blocked acquisition',async()=>{
 const value=input(),sourceReviews=[{...value.catalog.practiceSources[0],state:{enabled:true,dueAt:'2026-09-02T03:00:00.000Z'}}],before=structuredClone(sourceReviews);
 const result=await build({input:value,events:[await attempt('unknown')],sourceHashesByEventId:{},sourceReviews});assert.equal(result.fsrsMap['practice:one'].due,sourceReviews[0].state.dueAt);assert.equal(result.inventory[0].completedRounds,0);assert.match(result.inventory[0].blockedReason,/完成证据/);assert.ok(result.diagnostics.some(d=>d.code==='conditional-review-seed'));assert.ok(result.assumptions.some(a=>a.includes('初始参数')&&a.includes('不是实际')));
 const forecast=forecastLongTermReviews(result.inventory,result.fsrsMap,'2026-09-04',{asOfDate:value.day,generatedAt:'2026-08-31T00:00:00.000Z'});assert.equal(forecast.reviews[0].date,'2026-09-02');assert.deepEqual(sourceReviews,before);
});
test('incorrect partial and future events cannot complete; future scheduling cannot replay',async()=>{
 const events=[await attempt('wrong',undefined,{attempt:{rating:'again',correct:false,stageBefore:1,stageAfter:1}}),await attempt('partial',undefined,{attempt:{rating:'good',correct:true,stageBefore:0,stageAfter:1},scheduling:undefined}),await attempt('future','2026-09-01T00:00:00.000Z')];const result=await build({input:input(),events,sourceHashesByEventId:Object.fromEntries(events.map(e=>[e.eventId,hash]))});assert.equal(result.inventory[0].completedRounds,0);assert.deepEqual(result.history,[]);assert.deepEqual(result.fsrsMap,(await rebuildEventProgress(events.slice(0,2))).fsrsData);
});
test('same-day physical and unit aliases union once, and unversioned unit evidence cannot bypass source matching',async()=>{
 const value=input(),subject=value.catalog.subjects[1];subject.units=courseSubject(2).units;for(const unit of subject.units)Object.assign(unit,{action:{kind:'practice',itemKeys:['practice:one']},completionRule:'graded-practice'});value.completions=[{taskId:'unverified',unitId:'course:u0',occurredAt:'2026-08-28T03:00:00Z',basis:'practice-round'}];const events=[await attempt('one'),await attempt('alias'),await attempt('next','2026-08-31T03:00:00.000Z')];const result=await build({input:value,events,sourceHashesByEventId:Object.fromEntries(events.map(e=>[e.eventId,hash]))});assert.equal(result.inventory[0].completedRounds,2);assert.deepEqual(result.history.map(e=>e.completedRounds),[1,2]);
});
test('vocabulary history-unknown is never overwritten by complete practice evidence',async()=>{const value=vocabularyInput(1);value.words[0].status='history-unknown';const event=await attempt('word',undefined,{item:{kind:'word',key:'word:0'},domain:'ielts'});const result=await build({input:value,events:[event],sourceHashesByEventId:{word:'a'.repeat(64)}});assert.equal(result.inventory[0].completedRounds,0);assert.match(result.inventory[0].blockedReason,/历史/);assert.deepEqual(result.history,[]);});
test('unknown source provenance blocks zero-round acquisition without dropping a known due',async()=>{const result=await build({input:input(),events:[await attempt('unknown')],sourceHashesByEventId:{}});assert.match(result.inventory[0].blockedReason,/来源版本/);assert.ok(result.diagnostics.some(d=>d.code==='unknown-event-source'));});
test('an incomplete multi-item unit cannot gain drift history from only one complete physical item',async()=>{const value=input();value.catalog.subjects[1].units=courseSubject(1).units;Object.assign(value.catalog.subjects[1].units[0],{completionRule:'graded-practice',action:{kind:'practice',itemKeys:['practice:one','missing:two']}});const result=await build({input:value,events:[await attempt('one')],sourceHashesByEventId:{one:hash}});assert.equal(result.inventory.find(i=>i.itemId==='course:u0').completedRounds,0);assert.ok(!result.history.some(e=>e.itemId==='course:u0'));});
test('current source horizon overrides incomplete replay while parameters remain conditional',async()=>{
 const value=input(),events=[await attempt('old','2026-08-28T03:00:00.000Z'),await attempt('unknown')],sourceReviews=[{...value.catalog.practiceSources[0],state:{enabled:true,dueAt:'2026-09-05T03:00:00.000Z'}}];
 const result=await build({input:value,events,sourceHashesByEventId:{old:hash},sourceReviews});assert.equal(result.fsrsMap['practice:one'].due,sourceReviews[0].state.dueAt);assert.ok(result.diagnostics.some(d=>d.code==='conditional-review-seed'));assert.equal(result.inventory[0].completedRounds,1);
});
test('source observation older than verified scheduling cannot rewind the post-review horizon',async()=>{
 const value=input(),event=await attempt('new'),sourceReviews=[{...value.catalog.practiceSources[0],state:{enabled:true,dueAt:'2026-08-25T03:00:00.000Z'}}];
 const args={input:value,events:[event],sourceHashesByEventId:{new:hash},sourceReviews,sourceReviewsObservedAt:'2026-08-29T03:00:00.000Z'};
 assert.deepEqual((await build(args)).fsrsMap,(await rebuildEventProgress([event])).fsrsData);
 const later=await build({...args,sourceReviewsObservedAt:'2026-08-31T03:00:00.000Z'});assert.equal(later.fsrsMap['practice:one'].due,sourceReviews[0].state.dueAt);assert.ok(later.diagnostics.some(d=>d.code==='conditional-review-seed'));
});
test('outstanding daily obligations retain due and blocked uncertainty without inventing rounds',async()=>{
 const value=input();value.reviews=[{roundId:'missing-proof',itemKey:'practice:one',subjectId:'course',completionRule:'graded-practice',dueAt:'2026-08-29T03:00:00.000Z',completed:false,blockedReason:'来源证据缺失'}];const before=structuredClone(value);const result=await build({input:value,events:[await attempt('unknown')],sourceHashesByEventId:{}});
 assert.equal(result.fsrsMap['practice:one'].due,value.reviews[0].dueAt);assert.equal(result.inventory[0].completedRounds,0);assert.match(result.inventory[0].blockedReason,/来源证据缺失/);assert.ok(result.diagnostics.some(d=>d.code==='unresolved-review-obligation'));assert.deepEqual(value,before);
});
test('completed obligations do not create forecast and unresolved aliases retain earliest due once',async()=>{
 const value=input(),base={itemKey:'practice:one',subjectId:'course',completionRule:'graded-practice'};value.reviews=[{...base,roundId:'done',dueAt:'2026-08-25T03:00:00.000Z',completed:true},{...base,roundId:'later',dueAt:'2026-08-30T03:00:00.000Z',completed:false},{...base,roundId:'earlier',dueAt:'2026-08-29T03:00:00.000Z',completed:false}];const result=await build({input:value,events:[],sourceHashesByEventId:{}});assert.equal(result.fsrsMap['practice:one'].due,'2026-08-29T03:00:00.000Z');assert.equal(Object.keys(result.fsrsMap).length,1);assert.equal(result.inventory[0].completedRounds,0);
});
test('vanished source unresolved review remains blocked forecast workload under an unverified identity',async()=>{
 const value=input();value.reviews=[{roundId:'lost',itemKey:'removed:one',subjectId:'course',completionRule:'graded-practice',dueAt:'2026-08-28T03:00:00.000Z',completed:false,blockedReason:'来源已移除'}];const result=await build({input:value,events:[],sourceHashesByEventId:{}}),item=result.inventory.find(i=>i.itemId!=='practice:one');assert.ok(item);assert.equal(item.completedRounds,0);assert.notEqual(item.sourceHash,hash);assert.match(item.blockedReason,/来源已移除/);assert.equal(result.fsrsMap[item.itemId].due,value.reviews[0].dueAt);assert.deepEqual(result.history,[]);
});
test('unverified missing-subject workload passes the real preview without fresh acquisition',async()=>{
 const value=vocabularyInput(0);value.reviews=[{roundId:'orphan',itemKey:'removed',subjectId:'removed-subject',completionRule:'graded-practice',dueAt:'2026-08-28T03:00:00.000Z',completed:false}];const source=await build({input:value,events:[],sourceHashesByEventId:{}}),item=source.inventory[0];const {defaultLongTermSpec,previewLongTermPlan}=await import('../app/long-term-editor-model.ts');const spec=defaultLongTermSpec(value.day,source.subjects,'review-only');spec.targetDeadline=spec.startDate;const plan=previewLongTermPlan({spec,previous:null,source,today:value.day,generatedAt:'2026-08-31T12:00:00.000Z'});assert.ok(source.subjects.some(s=>s.subjectId===item.subjectId));assert.equal(source.bindings[0].itemId,item.itemId);assert.deepEqual(plan.schedule[0].newItemIds,[]);assert.deepEqual(plan.schedule[0].reviewItemIds,[item.itemId]);assert.match(source.diagnostics.find(d=>d.code==='unresolved-review-obligation').message,/unverified-review-obligation/);
});
test('unresolved demand remains due even alongside a later current-source horizon',async()=>{
 const value=input();value.reviews=[{roundId:'still-open',itemKey:'practice:one',subjectId:'course',completionRule:'graded-practice',dueAt:'2026-08-29T03:00:00.000Z',completed:false}];const sourceReviews=[{...value.catalog.practiceSources[0],state:{enabled:true,dueAt:'2026-09-05T03:00:00.000Z'}}];const args={input:value,events:[await attempt('old','2026-08-28T03:00:00.000Z')],sourceHashesByEventId:{old:hash},sourceReviews,sourceReviewsObservedAt:'2026-08-31T03:00:00.000Z'},before=structuredClone(args);const result=await build(args);assert.equal(result.fsrsMap['practice:one'].due,value.reviews[0].dueAt);assert.equal(result.inventory[0].completedRounds,1);assert.deepEqual(args,before);
});
test('same-instant source observation precedes a successful attempt in the real daily projector',async()=>{
 const {projectReviewObligations}=await import('../app/task-review-projection.ts');const value=input(),at='2026-08-31T03:00:00.000Z',event=await attempt('tie',at),sourceReviews=[{...value.catalog.practiceSources[0],state:{enabled:true,dueAt:'2026-08-25T03:00:00.000Z'}}];
 value.reviews=await projectReviewObligations({day:value.day,words:value.words,events:[event],previous:[],catalog:value.catalog,currentSourceReviews:sourceReviews,sourceObservedAt:at});
 assert.ok(value.reviews.some(r=>r.dueAt===sourceReviews[0].state.dueAt&&r.completed));const outstanding=value.reviews.find(r=>!r.completed);assert.equal(outstanding.dueAt,'2026-08-31T03:10:00.000Z');
 const source=await build({input:value,events:[event],sourceHashesByEventId:{tie:hash},sourceReviews,sourceReviewsObservedAt:at}),replay=await rebuildEventProgress([event]);assert.deepEqual(source.fsrsMap,replay.fsrsData);assert.equal(source.fsrsMap['practice:one'].due,outstanding.dueAt);assert.equal(source.inventory[0].completedRounds,1);assert.ok(!source.diagnostics.some(d=>d.code==='conditional-review-seed'));
});
