import {after} from 'node:test';
const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('external-fetch-denied-in-tests');};after(()=>{globalThis.fetch=originalFetch;});
import test from 'node:test';import assert from 'node:assert/strict';
import {studyAIConversationMessages,createStudyAIService,decodeStudyAIStream,studyAIHistoryKey,readStudyAIHistory,writeStudyAIHistory,StudyAIRequestGate} from '../app/ai/study-ai-service.ts';
test('normalized SSE handles Unicode splits, completion, error and abort',async()=>{const bytes=new TextEncoder().encode('data: {"type":"delta","text":"公式你好"}\n\ndata: {"type":"done","model":"actual","provider":"chatgpt"}\n\n');for(let split=1;split<bytes.length;split++){const r=new Response(new ReadableStream({start(c){c.enqueue(bytes.slice(0,split));c.enqueue(bytes.slice(split));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});const events=[];for await(const e of decodeStudyAIStream(r,new AbortController().signal))events.push(e);assert.equal(events[0].text,'公式你好');assert.equal(events[1].model,'actual');}await assert.rejects(async()=>{for await(const e of decodeStudyAIStream(new Response('data: {"type":"error"}\n\n',{headers:{'Content-Type':'text/event-stream'}}),new AbortController().signal))void e;},/provider/);});
test('history is separate by owner library provider and conversation and excludes credential fields',()=>{const scope={mode:'account',ownerId:'one',libraryId:'lib'},keys=[studyAIHistoryKey(scope,'deepseek','a'),studyAIHistoryKey({...scope,ownerId:'two'},'deepseek','a'),studyAIHistoryKey({...scope,libraryId:'other'},'deepseek','a'),studyAIHistoryKey(scope,'chatgpt','a'),studyAIHistoryKey(scope,'deepseek','b')];assert.equal(new Set(keys).size,5);const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};writeStudyAIHistory(storage,keys[0],[{id:'a',role:'user',content:'hello',providerKey:'forbidden'}]);assert.doesNotMatch(values.get(keys[0]),/forbidden|providerKey/);assert.equal(readStudyAIHistory(storage,keys[1]).length,0);});
test('context invalidation aborts old work and old scope cannot accept late results',()=>{const gate=new StudyAIRequestGate(),first=gate.begin();gate.invalidate();assert.equal(first.current(),false);assert.equal(first.signal.aborted,true);const second=gate.begin();assert.equal(second.current(),true);gate.invalidate();});
test('service uses real endpoint transport and rejects stale configuration',async()=>{let call;const service=createStudyAIService({request:async(...args)=>{call=args;return{status:'stale'};}});await assert.rejects(service.configure({expectedRevision:4}),/stale/);assert.equal(call[0],'configure');});

test('retry after an early failure excludes empty assistant placeholders',()=>{assert.deepEqual(studyAIConversationMessages([{id:'1',role:'user',content:'Hint'},{id:'2',role:'assistant',content:''},{id:'3',role:'user',content:'Try again'}]),[{role:'user',content:'Hint'},{role:'user',content:'Try again'}]);});
