'use client';
import type {LongTermPlanSpec} from './long-term-plan-types';
import type {LongTermEditorSource} from './long-term-editor-model';
import {MinimumQuotaControls,PracticeBudgetControls} from '../src/features/planning';
import {LongTermAIPlanner} from './long-term-ai-planner';

export function LongTermPlanForm({spec,source,tomorrow,startLocked,busy,active,onChange,onAISettings,currentSourceStamp,onAIBusyChange}:{spec:LongTermPlanSpec;source:LongTermEditorSource;tomorrow:string;startLocked:boolean;busy:boolean;active:boolean;onChange:(next:LongTermPlanSpec)=>void;onAISettings?:()=>void;currentSourceStamp:()=>string;onAIBusyChange?:(busy:boolean)=>void}){
 const subjects=spec.subjectsConfig.map(s=>({subjectId:s.subjectId,name:source.subjects.find(row=>row.subjectId===s.subjectId)?.name??'已有学科',itemCount:source.bindings.filter(b=>b.subjectId===s.subjectId).length,vocabularyCount:source.bindings.filter(b=>b.subjectId===s.subjectId&&b.kind==='vocabulary').length}));
 function changeSubject(index:number,patch:Partial<LongTermPlanSpec['subjectsConfig'][number]>){const next=structuredClone(spec);next.subjectsConfig[index]={...next.subjectsConfig[index],...patch};if(next.subjectsConfig[index].dailyQuotaTarget===undefined)delete next.subjectsConfig[index].dailyQuotaTarget;onChange(next);}
 return <>
  <LongTermAIPlanner planningStart={tomorrow} spec={spec} subjects={subjects} active={active} disabled={busy} onApply={onChange} onSettings={onAISettings} currentSourceStamp={currentSourceStamp} onBusyChange={onAIBusyChange}/>
  <MinimumQuotaControls spec={spec} wordSubjects={subjects.filter(s=>s.vocabularyCount>0&&s.vocabularyCount===s.itemCount).map(s=>s.subjectId)} busy={busy} onChange={onChange}/>
  <PracticeBudgetControls spec={spec} subjects={subjects} busy={busy} onChange={onChange}/>
  <section className="long-term-form-section" aria-label="目标与时间"><h4><span>01</span> 什么时候完成，每天有多少时间</h4><div className="long-term-fields long-term-primary-fields">
   <label>开始日期<input type="date" value={spec.startDate} min={tomorrow} disabled={busy||startLocked} onChange={e=>onChange({...spec,startDate:e.target.value})}/><small>{startLocked?'已有目标保留起点':'新目标从明天开始'}</small></label>
   <label>目标完成日期<input type="date" value={spec.targetDeadline} min={spec.startDate>tomorrow?spec.startDate:tomorrow} disabled={busy} onChange={e=>onChange({...spec,targetDeadline:e.target.value})}/><small>放不下的内容会单独提示</small></label>
   <label>工作日参考时间<input type="number" min="0" max="1440" step="5" value={spec.dailyMinutesBudget.workdayMax} disabled={busy} onChange={e=>onChange({...spec,dailyMinutesBudget:{...spec.dailyMinutesBudget,workdayMax:Number(e.target.value),workdayMin:Math.min(spec.dailyMinutesBudget.workdayMin,Number(e.target.value))}})}/><small>分钟 · 新学和复习合计</small></label>
   <label>周末参考时间<input type="number" min="0" max="1440" step="5" value={spec.dailyMinutesBudget.weekendMax} disabled={busy} onChange={e=>onChange({...spec,dailyMinutesBudget:{...spec.dailyMinutesBudget,weekendMax:Number(e.target.value)}})}/><small>分钟 · 可以和工作日不同</small></label>
  </div></section>
  <section className="long-term-form-section" aria-label="每天复习多少"><h4><span>02</span> 每天先复习多少</h4><div className="long-term-review-setting"><label>每日复习目标<input aria-label="每日复习目标（条）" type="number" min="0" max="10000" step="1" value={spec.dailyReviewTarget??''} placeholder="例如 20" disabled={busy} onChange={e=>{const next={...spec};if(e.target.value==='')delete next.dailyReviewTarget;else next.dailyReviewTarget=Number(e.target.value);onChange(next);}}/><small>条 / 天 · 各学科合计</small></label><div><strong>这是目标，可以追加。</strong><p>到期内容超过目标时，会显示“还有多少条待复习”，你可以追加到今天。没有到期内容时不会为了凑数提前复习。留空表示先显示全部到期内容。</p></div></div></section>
  <section className="long-term-form-section" aria-label="各学科每日学习量"><h4><span>03</span> 每天学多少，优先学什么</h4><p className="long-term-helper">新词和复习分开计数。最低目标先安排；标为上限的旧设置仍表示最多安排多少。资料不足会显示缺口。</p><div className="long-term-subjects long-term-friendly-subjects">
   {spec.subjectsConfig.map((s,index)=>{const info=subjects[index],words=info.vocabularyCount>0&&info.vocabularyCount===info.itemCount;return <fieldset key={s.subjectId}><legend>{info.name}<small>{words?`${info.vocabularyCount} 个词`:`${info.itemCount} 项内容`}</small></legend>
    <label>{words&&s.dailyMinimumTarget!==undefined?'每天至少新学单词':words?'每天最多新学单词':'每天最多新学内容'}<input aria-label={`${info.name}${words&&s.dailyMinimumTarget!==undefined?'每天至少新学单词':words?'每天新学单词':'每天新学内容'}`} type="number" min="0" max="10000" step="1" placeholder="按时间安排" value={(words&&s.dailyMinimumTarget!==undefined?s.dailyMinimumTarget:s.dailyQuotaTarget)??''} disabled={busy} onChange={e=>{const n=e.target.value===''?undefined:Number(e.target.value);changeSubject(index,words&&s.dailyMinimumTarget!==undefined?{dailyMinimumTarget:n??0,dailyQuotaTarget:n??0}:{dailyQuotaTarget:n});}}/><small>{words?'个新词 / 天':'项 / 天'} · 复习另算{words&&s.dailyMinimumTarget!==undefined?' · 还可自主加学':''}</small></label>
    <label>学科优先级<select value={s.priority} disabled={busy} onChange={e=>changeSubject(index,{priority:Number(e.target.value)})}>{[[5,'5 · 最优先'],[4,'4 · 较优先'],[3,'3 · 常规'],[2,'2 · 较低'],[1,'1 · 最后安排']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small>时间不够时，优先照顾高优先级</small></label>
    <label>目标留存率<input aria-label={`${info.name}目标留存率（%）`} type="number" min="70" max="99" step="1" value={Math.round((s.forecastRetention??.9)*100)} disabled={busy} onChange={e=>changeSubject(index,{forecastRetention:Number(e.target.value)/100})}/><small>% · 越高通常需要越频繁复习</small></label>
   </fieldset>;})}
  </div></section>
  <details className="long-term-advanced"><summary>高级设置 <span>时间分配与完成标准 · 保留原有选项</span></summary><p>不确定时可以保持默认。下面这些设置主要影响预测，不会代替你的真实练习记录。</p><div className="long-term-fields">
   <label>工作日期望至少学<input type="number" min="0" max={spec.dailyMinutesBudget.workdayMax} step="5" value={spec.dailyMinutesBudget.workdayMin} disabled={busy} onChange={e=>onChange({...spec,dailyMinutesBudget:{...spec.dailyMinutesBudget,workdayMin:Number(e.target.value)}})}/><small>分钟 · 默认估时仅供参考，不会硬凑任务</small></label>
   <label>为复习预留的时间<input type="number" min="0" max="100" step="5" value={Math.round(spec.dailyMinutesBudget.minReviewRatio*100)} disabled={busy} onChange={e=>onChange({...spec,dailyMinutesBudget:{...spec.dailyMinutesBudget,minReviewRatio:Number(e.target.value)/100}})}/><small>% · 例如 60 分钟的 30% 为 18 分钟，避免新学占满时间</small></label>
   <label>减少弹性任务的天数占比<input type="number" min="0" max="100" step="5" value={Math.round(spec.bufferRatio*100)} disabled={busy} onChange={e=>onChange({...spec,bufferRatio:Number(e.target.value)/100})}/><small>% · 原“缓冲日期”；例如 10 天的 20% 为 2 天</small></label>
  </div><div className="long-term-completion-settings">{spec.subjectsConfig.map((s,index)=><fieldset key={s.subjectId}><legend>{subjects[index].name} · 完成标准</legend><label>怎样算达到目标<select value={s.completionCriteria} disabled={busy} onChange={e=>changeSubject(index,{completionCriteria:e.target.value as 'fixed-rounds'|'all-mastered'})}><option value="fixed-rounds">完成指定练习轮数</option><option value="all-mastered">知识库中全部标记为已掌握</option></select></label>{s.completionCriteria==='fixed-rounds'&&<label>至少完成几轮<input type="number" min="1" max="1000" step="1" value={s.requiredRounds??1} disabled={busy} onChange={e=>changeSubject(index,{requiredRounds:Number(e.target.value)})}/></label>}<p>轮数来自真实记录；排入日程不等于完成。达到指定轮数也不等于保证掌握。</p></fieldset>)}</div></details>
 </>;
}
