"use client";
import {useEffect,useRef,useState} from 'react';
import {StudyPanel} from './study-session-shell';
import './note-sources.css';

type Source={sourceId:string;revision:number;label:string;kind:string;enabled:boolean;itemCount:number;lastRead:string|null;message:string;selection:Record<string,unknown>;writeback:null|{written:number;pending:number;uncertain:number;uncertainPages:number;message:string}};
type Preview={previewId:string;documentCount:number;itemCount:number;writeEnabled:boolean;samples:{title:string;kind:string;reference:string}[]};
type Setup={revision:string;mode:string;path:string;available:boolean};
type Props={endpoint:string;token:string|null;capabilities:string[];onChanged:()=>void;onDetected:(capabilities:string[])=>void};
export function NoteSourcesPanel(props:Props){
  // Remount on owner/session change so pending previews and credentials cannot
  // cross into another account's controls.
  return <NoteSourcesSession key={props.endpoint+':'+(props.token??'')} {...props}/>;
}
function NoteSourcesSession({endpoint,token,capabilities,onChanged,onDetected}:Props){
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [sources,setSources]=useState<Source[]>([]),[setup,setSetup]=useState<Setup|null>(null),[workspace,setWorkspace]=useState('');
  const [kind,setKind]=useState('folder'),[label,setLabel]=useState(''),[path,setPath]=useState(''),[pages,setPages]=useState(''),[secret,setSecret]=useState(''),[writePage,setWritePage]=useState(''),[writeEnabled,setWriteEnabled]=useState(false),[encoding,setEncoding]=useState('auto');
  const [editing,setEditing]=useState<Source|null>(null),[preview,setPreview]=useState<Preview|null>(null),[confirmed,setConfirmed]=useState(false);
  const lifetime=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();lifetime.current=controller;return()=>{controller.abort();lifetime.current=null;};},[]);
  const supported=capabilities.includes('note-sources-v1');
  async function request<T>(route:string,body?:unknown):Promise<T>{
    if(!token||!lifetime.current)throw new Error('请先配对本机 Companion。');
    const response=await fetch(endpoint+route,{method:body?'POST':'GET',headers:{'X-Study-Loop-Session':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.any([lifetime.current.signal,AbortSignal.timeout(150000)]),cache:'no-store'});
    const value=await response.json() as {message?:string;error?:string};if(!response.ok){const code=typeof value.error==='string'&&/^[a-z][a-z0-9-]{2,80}$/.test(value.error)?'（'+value.error+'）':'';throw new Error((value.message||'操作未完成，请检查 Companion。')+code);}return value as T;
  }
  async function read(){const [status,list]=await Promise.all([request<Setup>('/v1/setup'),request<{sources:Source[]}>('/v1/note-sources')]);if(!lifetime.current)return;setSetup(status);setWorkspace(status.path);setSources(list.sources);}
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(lifetime.current)setError(e instanceof TypeError?'网页无法连接本机 Companion，请检查程序是否仍在运行、端口是否一致，以及浏览器的本地网络访问权限。':e instanceof Error&&e.name==='TimeoutError'?'本机 Companion 请求超时，请确认窗口仍在运行，并一次只预览一个 Notion 页面。':e instanceof Error?e.message:'操作未完成。');}finally{if(lifetime.current)setBusy(false);}}
  function invalidate(){setPreview(null);setConfirmed(false);}
  function edit(source:Source){setEditing(source);setKind(source.kind);setLabel(source.label);setPath(String(source.selection.path??''));setPages((source.selection.pages as string[]??[]).join('\n'));setWritePage(String(source.selection.writePage??''));setWriteEnabled(source.selection.writeEnabled===true);setEncoding(String(source.selection.encoding??'auto'));setSecret('');invalidate();}
  function reset(){setEditing(null);setLabel('');setPath('');setPages('');setSecret('');setWritePage('');setWriteEnabled(false);invalidate();}
  async function makePreview(){
    const selection={kind,label,encoding,...(editing?{sourceId:editing.sourceId,expectedRevision:editing.revision}:{}),...(kind==='notion'?{pages:pages.split(/\r?\n/).map(p=>p.trim()).filter(Boolean),...(secret?{token:secret}:{}),writeEnabled,...(writeEnabled?{writePage}:{} )}:{path})};
    const result=await request<{preview:Preview}>('/v1/note-sources',{action:'preview',selection});if(lifetime.current){setSecret('');setPreview(result.preview);setConfirmed(false);}
  }
  return <section className="note-sources-entry"><div><h3>连接你的笔记</h3><p>文件夹、导出文件或 Notion 页面，持续同步到你的学习空间。</p></div>{!token?<a href="#companion-pairing">先安装并配对 →</a>:!supported?<div><p>请升级 Companion 后重新检测连接，以使用多来源同步。</p><a href="/downloads/Zhixue-Companion-Setup.exe" download>下载安装更新</a><button className="study-secondary-action" disabled={busy} onClick={()=>void run(async()=>{const health=await request<{capabilities?:string[]}>('/v1/health');if(!lifetime.current)return;const values=Array.isArray(health.capabilities)?health.capabilities.filter(value=>typeof value==='string'):[];onDetected(values);if(!values.includes('note-sources-v1'))setNotice('当前运行的仍是旧版，请关闭旧窗口并从原安装目录重新启动。');})}>更新后重新检测</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div>:<button className="study-secondary-action" onClick={()=>{setOpen(true);void run(read);}}>管理笔记来源</button>}
    <StudyPanel open={open} onClose={()=>{setOpen(false);setSecret('');invalidate();}} title="笔记来源与学习空间"><div className="note-sources">
      <p>原笔记保留在原位置。知学在本机学习空间保存练习和记录；启用账号同步后，提取的学习内容会同步到你的账号。</p>
      {setup&&<section><h3>1 · 学习空间</h3><p>{setup.mode==='managed'?'Companion 独立学习空间，无需安装 Obsidian':'你选择的本机学习库'} · {setup.available?'可访问':'当前无法访问'}</p><p className="note-source-path">{setup.path}</p><details><summary>使用已有学习库目录</summary><p>仅适用于尚未登记来源或保存学习记录的安装。已有记录时保留原学习空间，可在下方添加新资料目录。</p><label>已有学习库的完整目录<input value={workspace} onChange={e=>setWorkspace(e.target.value)} disabled={busy}/></label><button disabled={busy||workspace===setup.path||!workspace.trim()} onClick={()=>void run(async()=>{await request('/v1/setup',{expectedRevision:setup.revision,mode:'existing',path:workspace,confirmed:true});await read();onChanged();setNotice('学习空间已更新。');})}>确认使用此目录保存学习记录</button></details></section>}
      <section><h3>2 · {editing?'更新来源':'添加来源'}</h3><fieldset disabled={busy} onChange={invalidate}>
        <div className="note-source-fields"><label>来源类型<select value={kind} disabled={!!editing} onChange={e=>setKind(e.target.value)}><option value="folder">普通笔记 / Obsidian 文件夹</option><option value="file">单个学习文件</option><option value="notion-export">Notion 导出 ZIP</option><option value="notion">Notion 在线页面</option></select></label><label>来源名称<input value={label} maxLength={120} onChange={e=>setLabel(e.target.value)} placeholder="例如：机器学习课堂笔记"/></label></div>
        {kind==='notion'?<><label>来源页面链接，每行一个（最多 10 个）<textarea rows={3} value={pages} onChange={e=>setPages(e.target.value)} placeholder="https://www.notion.so/…"/></label><p>先连接一个具体页面并预览。只读取所列页面，不自动遍历工作区或整个数据库；请在 Notion 页面菜单中添加对应连接并允许读取内容。</p><label>Notion 授权令牌{editing?'（留空沿用已保存授权）':''}<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)}/></label><p>授权保存到本机系统凭据库。可使用个人访问令牌或内部连接令牌；网页登录 Notion、复制分享链接并不等于已授权 API 连接。</p><p>默认只读取资料；预览成功后，需要保存学习记录时再启用下方选项。</p><label className="note-source-check"><input type="checkbox" checked={writeEnabled} onChange={e=>setWriteEnabled(e.target.checked)}/>将学习记录和论文阅读笔记保存到 Notion</label>{writeEnabled&&<><label>独立的学习记录父页面链接<input value={writePage} onChange={e=>setWritePage(e.target.value)}/></label><p>请授权此页面的读取和新增内容权限。知学会在其中按日建立记录页；原始教材不会被修改。</p></>}</>:<><label>{kind==='folder'?'笔记文件夹完整路径':kind==='notion-export'?'Notion Markdown + CSV 导出 ZIP 路径':'文件完整路径'}<input value={path} onChange={e=>setPath(e.target.value)} placeholder={'C:\\Users\\你的用户名\\Documents\\笔记'}/></label><p>支持 Markdown、TXT、HTML、CSV、可提取文字的 PDF，以及知学导出的 .zhixue-candidates.json 复测候选文件（需新版 Companion）。其他笔记软件可导出这些格式后接入；云盘文件请先下载到本机。</p><label>文字编码<select value={encoding} onChange={e=>setEncoding(e.target.value)}><option value="auto">自动识别（UTF-8 / UTF-16）</option><option value="gb18030">简体中文旧文件（GB18030）</option><option value="utf-8">UTF-8</option><option value="utf-16">UTF-16</option></select></label></>}
        <div className="note-source-actions"><button disabled={!label.trim()} onClick={()=>void run(makePreview)}>预览可学习内容</button>{editing&&<button onClick={reset}>取消更新，添加新来源</button>}</div>
      </fieldset>
      {preview&&<div className="note-source-preview"><h4>已完整读取 {preview.documentCount} 篇，提取 {preview.itemCount} 条</h4>{preview.samples.map((sample,index)=><article key={index}><strong>{sample.title}</strong><p>{sample.reference}</p></article>)}<label className="note-source-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>确认将这些内容加入学习空间{preview.writeEnabled?'，并向指定 Notion 页面写入实际练习记录':''}</label><button disabled={busy||!confirmed} onClick={()=>void run(async()=>{await request('/v1/note-sources',{action:'commit',previewId:preview.previewId,confirmed:true});if(!lifetime.current)return;reset();await read();onChanged();setNotice('来源已保存，自动同步已启用。');})}>确认接入并开始自动同步</button></div>}
      </section><section><h3>3 · 同步状态</h3><button disabled={busy} onClick={()=>void run(read)}>刷新状态</button>{!sources.length&&<p>尚未添加来源。先在上方预览并确认。</p>}{sources.map(source=><article className="note-source-row" key={source.sourceId}><h4>{source.label} · {source.enabled?'已启用':'已停用'}</h4><p>{source.itemCount} 条 · 最近读取：{source.lastRead?new Date(source.lastRead).toLocaleString():'尚未完成'}</p>{source.message&&<p role="status">读取：{source.message}</p>}{source.writeback&&<><p>练习记录写回：已写入 {source.writeback.written} · 等待 {source.writeback.pending} · 待核对 {source.writeback.uncertain} · 页面待核对 {source.writeback.uncertainPages}</p>{source.writeback.message&&<p role="status">{source.writeback.message}</p>}</>}<div className="note-source-actions"><button disabled={busy||!source.enabled} onClick={()=>void run(async()=>{await request('/v1/note-sources',{action:'sync',sourceId:source.sourceId,expectedRevision:source.revision});await read();onChanged();})}>立即同步并核对</button><button disabled={busy} onClick={()=>edit(source)}>更新来源与授权</button><button disabled={busy} onClick={()=>void run(async()=>{await request('/v1/note-sources',{action:'enabled',sourceId:source.sourceId,expectedRevision:source.revision,enabled:!source.enabled});await read();onChanged();})}>{source.enabled?'停用来源，保留历史':'重新启用'}</button></div></article>)}<p>文件来源约每分钟检查；Notion 约每五分钟读取。Companion 运行且网络可用时自动进行，失败后保留上次完整资料。</p></section>
      {busy&&<p role="status">正在处理，请稍候…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    </div></StudyPanel></section>;
}
