'use client';
import {useEffect,useRef,useState} from 'react';
import {importPaperFile,paperFromSource} from './paper-import';
import {DISCIPLINES,type DisciplineId} from './learning-catalog';
import {verifiedPaperScope,type PaperDocument,type PaperLibraryCatalog,type PaperDestination} from './paper-library-client';
import type {PaperStudyData,PaperDraft} from './paper-study';
import {savePaperNote} from './paper-note-save';
import type {PaperServices} from './plugins/plugin-paper';
import type {PaperDraftSession} from './paper-draft-store';
export function PaperSourcesPanel({services,onImport}:{services:PaperServices;onImport:(paper:PaperStudyData)=>Promise<void>}){
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'upload'|'vault'|'notion'>('upload'),[catalog,setCatalog]=useState<PaperLibraryCatalog|null>(null),[query,setQuery]=useState(''),[preview,setPreview]=useState<PaperStudyData|null>(null),[discipline,setDiscipline]=useState<DisciplineId>('other'),[busy,setBusy]=useState(false),[error,setError]=useState('');const epoch=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function run<T>(action:()=>Promise<T>,apply:(value:T)=>void){const id=++epoch.current;setBusy(true);setError('');try{const value=await action();if(alive.current&&id===epoch.current)apply(value);}catch(e){if(alive.current&&id===epoch.current)setError(e instanceof Error?e.message:'资料读取失败。');}finally{if(alive.current&&id===epoch.current)setBusy(false);}}
 function browse(kind:'vault'|'notion'){setTab(kind);setPreview(null);if(!services.libraryClient){setError('连接 Companion 后可读取 Obsidian 和 Notion；现在也可以直接上传文件。');return;}void run(()=>services.libraryClient!.catalog(query),value=>{verifiedPaperScope(value,services);setCatalog(value);});}
 function read(source:PaperDocument){if(!services.libraryClient||!catalog)return;const scope=verifiedPaperScope(catalog,services);void run(()=>services.libraryClient!.read(source,scope),value=>{setPreview(paperFromSource(value));setDiscipline('other');});}
 return <section className="paper-source-picker"><div className="paper-source-heading"><div><h2>论文资料库</h2><p>从笔记中选择，或上传自己的论文；先核对正文，再开始阅读。</p></div><button onClick={()=>setOpen(value=>!value)}>{open?'收起资料选择':'选择论文 / 上传文件'}</button></div>{open&&<><div className="paper-source-tabs" role="tablist" aria-label="论文来源"><button role="tab" aria-selected={tab==='upload'} onClick={()=>{epoch.current++;setBusy(false);setTab('upload');setPreview(null);setError('');}}>上传文件</button><button role="tab" aria-selected={tab==='vault'} onClick={()=>browse('vault')}>Obsidian / 本机</button><button role="tab" aria-selected={tab==='notion'} onClick={()=>browse('notion')}>Notion</button></div>
  {tab==='upload'?<div className="paper-file-upload"><label>选择论文文件<input type="file" accept=".pdf,.md,.markdown,.txt,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>importPaperFile(file),value=>{setPreview(value);setDiscipline(value.disciplineId as DisciplineId??'other');});e.target.value='';}}/></label><p>支持 PDF、Markdown、TXT、原 lesson.json。PDF 在浏览器提取文字；扫描版需先做文字识别。</p></div>:<><form className="paper-source-search" onSubmit={e=>{e.preventDefault();browse(tab);}}><label>查找文件或来源<input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="输入标题或课程关键词"/></label><button disabled={busy||!services.libraryClient}>查找</button></form><div className="paper-source-documents">{catalog?.documents.filter(d=>d.kind===tab&&(tab==='vault'||!query||d.title.toLowerCase().includes(query.toLowerCase()))).map(d=><button key={JSON.stringify([d.kind,d.path,d.sourceId,d.pageId])} disabled={busy} onClick={()=>read(d)}><strong>{d.title}</strong><small>{d.path??d.url}</small></button>)}</div>{catalog?.limited&&<p>结果较多，当前最多展示 200 个文件；请用关键词缩小范围。</p>}{!catalog?.documents.some(d=>d.kind===tab)&&!busy&&<p>{tab==='notion'?'尚无已连接的 Notion 页面，请在资料连接中添加并授权具体页面。':'输入关键词查找学习库内的文件，或直接上传论文。'}</p>}<button onClick={services.onSources}>管理资料连接与 Notion 保存位置</button></>}
  {busy&&<p role="status">正在读取并整理正文…</p>}{error&&<p role="alert">{error}</p>}{preview&&<section className="paper-source-preview"><label>论文标题<input maxLength={400} value={preview.title} onChange={e=>setPreview({...preview,title:e.target.value})}/></label><p>{preview.sections.length} 个章节 / 页面 · {preview.sections.reduce((n,s)=>n+s.paragraphs.length,0)} 个阅读微段</p><label>归属学科<select value={discipline} onChange={e=>setDiscipline(e.target.value as DisciplineId)}>{Object.entries(DISCIPLINES).map(([id,value])=><option key={id} value={id}>{value.label}</option>)}</select></label><p>{preview.figures?.length?`已读取 ${preview.figures.length} 个登记图表，可在阅读中对照。`:'当前材料没有可用的登记图表，仍可继续阅读正文。'}</p><blockquote>{preview.sections[0].paragraphs[0].rawEn.slice(0,900)}</blockquote><p>请核对 PDF 分栏与正文顺序；文字提取不会自动生成释义或学习结论。</p><button className="paper-primary" disabled={busy} onClick={()=>void run(()=>onImport({...preview,disciplineId:discipline}),()=>{setPreview(null);setOpen(false);})}>确认材料并开始阅读</button></section>}</> }</section>;
}
export function PaperNoteSavePanel({services,paper,session,draft}:{services:PaperServices;paper:PaperStudyData;session:PaperDraftSession;draft:PaperDraft}){
 const [catalog,setCatalog]=useState<PaperLibraryCatalog|null>(null),[selection,setSelection]=useState(paper.origin?.kind==='notion'&&paper.origin.sourceId?paper.origin.sourceId:'obsidian'),[directory,setDirectory]=useState('02 项目与研究/论文阅读笔记'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const alive=useRef(true),working=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function destinations(){if(!services.libraryClient){setMessage('连接 Companion 后可保存到指定位置；完整草稿与 Markdown 导出仍可使用。');return;}setBusy(true);try{const result=await services.libraryClient.catalog();verifiedPaperScope(result,services);if(alive.current)setCatalog(result);}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'保存位置读取失败。');}finally{if(alive.current)setBusy(false);}}
 async function save(){
  if(working.current)return;working.current=true;setBusy(true);
  try{await savePaperNote(session,paper,{client:services.libraryClient,expected:services,catalog,selection,directory});if(alive.current)setMessage('本次阅读快照已保存。之后的修改请再次保存；这不会更新学习成绩。');}
  catch(error){if(alive.current)setMessage((error instanceof Error?error.message:'保存未完成。')+(session.snapshot().draft.pendingNote?' 原请求已保留，重试会核对同一次保存。':''));}
  finally{working.current=false;if(alive.current)setBusy(false);}
 }
 return <section className="paper-note-save"><h2>保存本次阅读</h2><p>保存当前主线模板、其他模板中已写的草稿、概括、自检和已选词汇。每次建立独立笔记，原论文保持原样。</p><div className="paper-note-destination"><label>保存到<select value={selection} disabled={busy||!!draft.pendingNote} onChange={e=>setSelection(e.target.value)}><option value="obsidian">Obsidian / 本机学习库</option>{selection!=='obsidian'&&!catalog&&<option value={selection}>Notion · 当前来源（读取保存位置）</option>}{catalog?.destinations.filter((d):d is Extract<PaperDestination,{kind:'notion'}>=>d.kind==='notion').map(d=><option key={d.sourceId} value={d.sourceId}>Notion · {d.label}</option>)}</select></label><button onClick={()=>void destinations()} disabled={busy}>读取已连接的位置</button>{selection==='obsidian'?<label>学习库内的保存目录<input maxLength={500} value={directory} disabled={busy||!!draft.pendingNote} onChange={e=>setDirectory(e.target.value)}/></label>:<p>保存到该 Notion 来源已指定的记录父页面；可在资料连接中更改。</p>}</div><div className="paper-actions"><button className="paper-primary" disabled={busy||!!session.snapshot().error} onClick={()=>void save()}>{busy?'正在保存…':draft.pendingNote?'重试原保存请求':'保存笔记与选词'}</button><button onClick={services.onSources}>连接或调整保存位置</button></div>{message&&<p role="status">{message}</p>}{draft.noteReceipt&&<p>最近保存：{draft.noteReceipt.path??<a href={draft.noteReceipt.url} target="_blank" rel="noreferrer">打开 Notion 阅读笔记</a>}</p>}</section>;
}
