/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors match established Vinext navigation. */
import type {Metadata} from 'next';
import './guide.css';
export const metadata:Metadata={title:'Companion 安装与更新指南 · 知学'};
export default function CompanionGuide(){return <main className="companion-guide">
 <nav><a href="/">知学</a><a href="/study">返回学习页 →</a></nav>
 <header><p className="guide-kicker">安装 · 连接 · 开始学习</p><h1>先装好 Companion，<br/>再接入一份自己的资料。</h1><p>Windows x64 专用。已附带运行环境，无需另外安装 Python、PowerShell 7 或 Obsidian。</p><div className="guide-actions"><a className="guide-primary" href="/downloads/Zhixue-Companion-Setup.exe" download>下载 Windows 安装包</a><a href="/downloads/companion-install-guide.md" download>保存离线教程</a></div><p className="guide-note">手机、平板和 Mac 不运行这个 EXE，可先使用网站支持的在线学习、浏览器上传和草稿功能。</p></header>
 <div className="guide-jumps"><a href="#first-install">第一次安装</a><a href="#update">已有用户更新</a><a href="#connect">连接资料</a><a href="#troubleshoot">遇到问题</a></div>
 <section id="first-install"><span className="guide-number">01</span><h2>第一次安装</h2><ol><li><strong>在 Windows 电脑下载并双击 EXE。</strong><p>如果询问以前是否安装过，首次安装选“否”；有旧版则选“是”，找到包含 server.py 的原文件夹。</p></li><li><strong>等待安装检查完成，再启动 Companion。</strong><p>看到本机端口和配对提示后，保留启动窗口，可最小化。</p></li><li><strong>从程序打开的首页进入学习，再登录配对。</strong><p>点击“进入学习”或“继续学习”，在设置中输入当前窗口的一次性配对码。首页会将实际端口带入学习页，避免连接到错误安装。</p></li><li><strong>接入一份小材料，核对结果。</strong><p>“数据与设置 → 连接你的笔记”，先预览、再确认。看到公开示例还不代表个人资料已经接入。</p></li></ol></section>
 <section id="update"><span className="guide-number">02</span><h2>已经安装过，只做更新</h2><p>在“设置与连接”顶部点击“下载更新 Companion”，下载后运行安装包。它会寻找旧目录，备份后更新程序。</p><ul><li>保留原安装目录、知识库和 data 文件夹；无需先卸载。</li><li>早期便携版请选择原来的文件夹，不要另建空安装来代替旧数据。</li><li>新窗口启动后，回网站“检测连接”或“重新连接／立即同步”。原配对有效时无需再配对。</li></ul><p className="guide-note">失败时保留错误信息与备份。备份在 Windows 用户本地应用数据目录的“Zhixue Companion Backups”文件夹。</p></section>
 <section id="connect"><span className="guide-number">03</span><h2>安装、配对、资料接入，分别核对</h2><div className="guide-checks"><article><h3>安装完成</h3><p>程序可以启动并显示端口与配对提示。</p></article><article><h3>网页已配对</h3><p>连接区显示“已配对”或“本机连接已经就绪”。</p></article><article><h3>自己的资料可用</h3><p>来源预览成功，学习页出现对应内容。</p></article></div><p>Obsidian 和普通目录从“连接你的笔记”接入；Notion 需授权具体页面，保存记录时另选记录父页面。论文工坊也可以直接上传 PDF、Markdown、TXT 和 JSON。</p><p>AI 可以稍后配置。没有模型密钥，不代表安装失败。</p><a href="/study?pair=1">前往网页连接区 →</a></section>
 <section id="troubleshoot"><span className="guide-number">04</span><h2>按现象排查</h2><details><summary>Windows 显示来源或信誉提示</summary><p>当前安装包尚未代码签名。核对下载来源并保留具体提示，不要关闭系统防护。工作或学校电脑受策略限制时，联系管理员。</p></details><details><summary>窗口一闪而过，或提示运行环境不可用</summary><p>使用最新安装包。失败窗口会保留错误信息；记录第一条错误与出错阶段，不要先删除 data，也不必先自行安装 Python。</p></details><details><summary>安装好了，网页仍提示未运行</summary><p>在开始菜单搜索“知学 Companion”，或从原目录运行 start-companion.cmd，保持窗口运行后重新检测。窗口正常但检测失败时，核对端口和浏览器对本网站的本地网络访问权限；可用设置中的“打开本机状态页”辅助检查。只打开网页不会自动启动本机程序。</p></details><details><summary>配对码无效，或连接端口不一致</summary><p>使用当前窗口的新配对码，登录原绑定账号。端口不是 43121 时，优先使用程序自动打开的网址，不要沿用旧收藏。</p></details><details><summary>已经配对，却仍是示例或没有内容</summary><p>检查是否在“连接你的笔记”中预览并确认资料。核对文件可访问、格式可识别，再立即同步。</p></details><details><summary>关闭窗口之后不能同步</summary><p>关闭 Companion 会暂停本机读取和写回，需要时重新启动；平时可最小化窗口。</p></details><details><summary>我需要便携 ZIP</summary><p>完整解压 ZIP，再运行 install-companion.cmd 或 upgrade-companion.cmd。不要在压缩包内运行，也不要只复制单个脚本。</p><a href="/downloads/zhixue-companion-windows.zip" download>下载便携 ZIP</a></details><p className="guide-note">反馈问题时附 Windows 版本、安装包版本、首次安装还是更新，以及去掉配对码、密钥和个人笔记后的错误信息。</p></section>
 <footer><a href="/study">回到知学，接入自己的资料 →</a></footer>
 </main>;}
