import type {CloudPlanningFactsV1} from '../app/account-study-planning';
import type {ContentDecision,ContentDecisionReceipt} from '../app/account-study-content-decision';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {parseCloudPlanningFacts} from '../app/account-study-planning.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {canonicalizeJson} from '../app/study-event-v3.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {studyCount,studyDigest,studyHash,studyId,studyObject} from '../app/account-study-content.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {parseContentDecisionReceipt} from '../app/account-study-content-decision.ts';
type D1=Pick<D1Database,'prepare'|'batch'>;type Scope={userId:string;libraryId:string};
type Row={sequence:number;user_id:string;library_id:string;operation_id:string;facts_hash:string;candidate_id:string;content_hash:string;decision:string;request_hash:string;status:string;received_at:string};
type ReceiptRow={sequence:number;user_id:string;library_id:string;receipt_id:string;operation_id:string;payload_hash:string;payload_json:string;writer_grant_id:string;received_at:string};
export type ContentDecisionOperation={sequence:number;operationId:string;factsHash:string;candidateId:string;contentHash:string;decision:ContentDecision;status:'pending'|'applied'|'blocked';receivedAt:string};
function a(scope:Scope):[string,string]{studyId(scope.userId,'user');studyId(scope.libraryId,'library');return[scope.userId,scope.libraryId];}
export class AccountStudyContentDecisionStore{
  private database:D1;constructor(database:D1){this.database=database;}private q(sql:string,...values:unknown[]){return this.database.prepare(sql).bind(...values);}
  private operation(row:Row,scope:Scope):ContentDecisionOperation{if(row.user_id!==scope.userId||row.library_id!==scope.libraryId||!Number.isSafeInteger(row.sequence)||row.sequence<1||!['approved','rejected','later'].includes(row.decision)||!['pending','applied','blocked'].includes(row.status))throw new Error('content-decision-integrity');studyId(row.operation_id);studyId(row.candidate_id);studyDigest(row.facts_hash);studyDigest(row.content_hash);return{sequence:row.sequence,operationId:row.operation_id,factsHash:row.facts_hash,candidateId:row.candidate_id,contentHash:row.content_hash,decision:row.decision as ContentDecision,status:row.status as ContentDecisionOperation['status'],receivedAt:row.received_at};}
  private async facts(scope:Scope,hash:string):Promise<CloudPlanningFactsV1>{studyDigest(hash);const row=await this.q('SELECT facts_json FROM account_study_planning_facts WHERE user_id=? AND library_id=? AND facts_hash=?',...a(scope),hash).first<{facts_json:string}>();if(!row)throw new Error('unknown-content-candidate-facts');return parseCloudPlanningFacts(JSON.parse(row.facts_json));}
  async decide(scope:Scope,raw:unknown):Promise<{status:'accepted'|'duplicate';operation:ContentDecisionOperation}>{const value=studyObject(raw,['operationId','factsHash','candidateId','contentHash','decision']);studyId(value.operationId,'operation');studyDigest(value.factsHash);studyId(value.candidateId,'candidate');studyDigest(value.contentHash);if(!['approved','rejected','later'].includes(String(value.decision)))throw new Error('invalid-content-decision');const requestHash=await studyHash(value),old=await this.q('SELECT * FROM account_study_content_decisions WHERE user_id=? AND library_id=? AND operation_id=?',...a(scope),value.operationId).first<Row>();if(old){if(old.request_hash!==requestHash)throw new Error('content-decision-conflict');return{status:'duplicate',operation:this.operation(old,scope)};}
    const facts=await this.facts(scope,value.factsHash as string),candidate=facts.contentCandidates.find(item=>item.candidateId===value.candidateId&&item.contentHash===value.contentHash);if(!candidate)throw new Error('unknown-content-candidate');const decision=this.q("INSERT INTO account_study_content_decisions(user_id,library_id,operation_id,facts_hash,candidate_id,content_hash,decision,request_hash,status) SELECT ?,?,?,?,?,?,?,?,'pending' WHERE "+(value.decision==='later'?"NOT EXISTS (SELECT 1 FROM account_study_content_decision_finals WHERE user_id=? AND library_id=? AND candidate_id=? AND content_hash=?)":"EXISTS (SELECT 1 FROM account_study_content_decision_finals WHERE user_id=? AND library_id=? AND candidate_id=? AND content_hash=? AND operation_id=?)"),...a(scope),value.operationId,value.factsHash,value.candidateId,value.contentHash,value.decision,requestHash,...a(scope),value.candidateId,value.contentHash,...(value.decision==='later'?[]:[value.operationId]));
    if(value.decision==='later')await decision.run();else await this.database.batch([this.q('INSERT INTO account_study_content_decision_finals(user_id,library_id,candidate_id,content_hash,operation_id,decision) VALUES(?,?,?,?,?,?) ON CONFLICT DO NOTHING',...a(scope),value.candidateId,value.contentHash,value.operationId,value.decision),decision]);const row=await this.q('SELECT * FROM account_study_content_decisions WHERE user_id=? AND library_id=? AND operation_id=?',...a(scope),value.operationId).first<Row>();if(!row){if(await this.q('SELECT operation_id FROM account_study_content_decision_finals WHERE user_id=? AND library_id=? AND candidate_id=? AND content_hash=?',...a(scope),value.candidateId,value.contentHash).first())throw new Error('content-decision-final');throw new Error('content-decision-storage-failed');}return{status:'accepted',operation:this.operation(row,scope)};}
  async list(scope:Scope,after:number,limit:number,through?:number):Promise<{operations:ContentDecisionOperation[];nextCursor:number|null;through:number}>{studyCount(after,'cursor');studyCount(limit,'limit',1);if(limit>20)throw new Error('invalid-decision-limit');const latest=await this.q('SELECT coalesce(max(sequence),0) AS value FROM account_study_content_decisions WHERE user_id=? AND library_id=?',...a(scope)).first<number>('value')??0,fence=through??latest;studyCount(fence,'fence');if(after>fence||fence>latest)throw new Error('invalid-decision-fence');const rows=(await this.q('SELECT * FROM account_study_content_decisions WHERE user_id=? AND library_id=? AND sequence>? AND sequence<=? ORDER BY sequence LIMIT ?',...a(scope),after,fence,limit+1).all<Row>()).results,operations=rows.slice(0,limit).map(row=>this.operation(row,scope));if(rows.length<=limit&&(operations.at(-1)?.sequence??after)!==fence)throw new Error('invalid-decision-fence');return{operations,nextCursor:rows.length>limit?operations.at(-1)!.sequence:null,through:fence};}
  async appendReceipt(scope:Scope,raw:unknown,writerGrantId:string):Promise<{status:'accepted'|'duplicate'|'conflict';execution:{sequence:number;receipt:ContentDecisionReceipt;writerGrantId:string;receivedAt:string}}>{studyId(writerGrantId,'grant');const receipt=await parseContentDecisionReceipt(raw),row=await this.q('SELECT * FROM account_study_content_decisions WHERE user_id=? AND library_id=? AND operation_id=?',...a(scope),receipt.operationId).first<Row>();if(!row)throw new Error('unknown-content-decision-operation');const operation=this.operation(row,scope);if(operation.candidateId!==receipt.candidateId||operation.contentHash!==receipt.contentHash||operation.decision!==receipt.decision)throw new Error('content-decision-receipt-binding');if(!await this.q("SELECT grant_id FROM account_study_grants WHERE user_id=? AND library_id=? AND grant_id=? AND state='active' AND expires_at>strftime('%Y-%m-%dT%H:%M:%fZ','now')",...a(scope),writerGrantId).first())throw new Error('study-writer-required');const hash=await studyHash(receipt),same=await this.q('SELECT payload_hash FROM account_study_content_decision_receipts WHERE user_id=? AND library_id=? AND receipt_id=?',...a(scope),receipt.receiptId).first<string>('payload_hash'),latest=await this.latest(scope,receipt.operationId);if(same){if(same===hash){const repairs=[this.q('UPDATE account_study_content_decisions SET status=? WHERE user_id=? AND library_id=? AND operation_id=?',receipt.status,...a(scope),receipt.operationId)];if(receipt.status==='blocked')repairs.push(this.q('DELETE FROM account_study_content_decision_finals WHERE user_id=? AND library_id=? AND candidate_id=? AND content_hash=? AND operation_id=?',...a(scope),receipt.candidateId,receipt.contentHash,receipt.operationId));await this.database.batch(repairs);}return{status:same===hash?'duplicate':'conflict',execution:latest!};}if(latest?.receipt.status==='applied'){const before={...latest.receipt,receiptId:''},next={...receipt,receiptId:''};return{status:canonicalizeJson(before)===canonicalizeJson(next)?'duplicate':'conflict',execution:latest};}
    await this.q("INSERT INTO account_study_content_decision_receipts(user_id,library_id,receipt_id,operation_id,status,payload_hash,payload_json,writer_grant_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING",...a(scope),receipt.receiptId,receipt.operationId,receipt.status,hash,canonicalizeJson(receipt),writerGrantId).run();const execution=await this.latest(scope,receipt.operationId);if(!execution)throw new Error('content-decision-receipt-storage-failed');if(execution.receipt.receiptId!==receipt.receiptId)return{status:'conflict',execution};const updates=[this.q('UPDATE account_study_content_decisions SET status=? WHERE user_id=? AND library_id=? AND operation_id=? AND EXISTS (SELECT 1 FROM account_study_content_decision_receipts WHERE user_id=? AND library_id=? AND operation_id=? AND receipt_id=? AND payload_hash=?)',receipt.status,...a(scope),receipt.operationId,...a(scope),receipt.operationId,receipt.receiptId,hash)];if(receipt.status==='blocked')updates.push(this.q('DELETE FROM account_study_content_decision_finals WHERE user_id=? AND library_id=? AND candidate_id=? AND content_hash=? AND operation_id=?',...a(scope),receipt.candidateId,receipt.contentHash,receipt.operationId));await this.database.batch(updates);return{status:'accepted',execution};}
  private async latest(scope:Scope,operationId:string){const row=await this.q('SELECT * FROM account_study_content_decision_receipts WHERE user_id=? AND library_id=? AND operation_id=? ORDER BY sequence DESC LIMIT 1',...a(scope),operationId).first<ReceiptRow>();if(!row)return null;const receipt=await parseContentDecisionReceipt(JSON.parse(row.payload_json));if(row.payload_hash!==await studyHash(receipt))throw new Error('content-decision-receipt-integrity');return{sequence:row.sequence,receipt,writerGrantId:row.writer_grant_id,receivedAt:row.received_at};}
}
