// @ts-expect-error TS5097: Node contract tests use explicit extensions.
import {providerEndpoint} from '../app/ai/study-ai-provider.ts';
import type {StudyAIProvider,StudyAISettings} from '../app/ai/study-ai-types';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {canonicalizeJson} from '../app/study-event-v3.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {studyCount,studyDigest,studyHash,studyId,studyObject,studyText} from '../app/account-study-content.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {decryptAccountAiKey,encryptAccountAiKey} from '../app/account-study-secret.ts';
// @ts-expect-error TS5097: Node contract tests execute explicit TypeScript extensions.
import {validPlanDay} from '../app/task-plan-types.ts';
type D1=Pick<D1Database,'prepare'|'batch'>;type Scope={userId:string;libraryId:string};
type Settings=StudyAISettings;
type StoredConfig={model:string;baseUrl:string;ciphertext?:string;nonce?:string};
type Configs=Partial<Record<StudyAIProvider,StoredConfig>>;
type RequestTrace={provider?:StudyAIProvider;operationKind:'plan'|'question'|'chat';modelId:string;promptVersion:string;ruleVersion:string};
function args(scope:Scope):[string,string]{studyId(scope.userId);studyId(scope.libraryId);return[scope.userId,scope.libraryId];}
function trace(raw:unknown):RequestTrace{const value=studyObject(raw,['operationKind','modelId','promptVersion','ruleVersion'],['provider']);if(!['plan','question','chat'].includes(String(value.operationKind)))throw new Error('invalid-ai-operation-kind');studyText(value.modelId,'ai-model-id',160);studyText(value.promptVersion,'ai-prompt-version',80);studyText(value.ruleVersion,'ai-rule-version',80);return structuredClone(value) as RequestTrace;}
export class AccountStudyAiStore{
  private database:D1;private encryptionKey:string;constructor(database:D1,encryptionKey=''){this.database=database;this.encryptionKey=encryptionKey;}private q(sql:string,...values:unknown[]){return this.database.prepare(sql).bind(...values);}
  async getSettings(scope:Scope):Promise<Settings>{
    await this.q('INSERT INTO account_study_ai_settings(user_id,library_id) VALUES(?,?) ON CONFLICT DO NOTHING',...args(scope)).run();
    const row=await this.q('SELECT * FROM account_study_ai_settings WHERE user_id=? AND library_id=?',...args(scope)).first<{unlimited_daily_usage:number;enabled:number;daily_request_limit:number;daily_token_limit:number;concurrent_limit:number;max_output_tokens:number;credential_ciphertext:string|null;credential_nonce:string|null;revision:number;provider:StudyAIProvider;provider_configs:string}>();
    if(!row||![0,1].includes(row.unlimited_daily_usage)||![0,1].includes(row.enabled)||(row.credential_ciphertext===null)!==(row.credential_nonce===null))throw new Error('ai-settings-integrity');studyCount(row.daily_request_limit,'daily-limit',1);studyCount(row.daily_token_limit,'daily-token-limit',100);studyCount(row.concurrent_limit,'concurrent-limit',1);studyCount(row.max_output_tokens,'max-tokens',100);studyCount(row.revision,'revision');
    const configs=JSON.parse(row.provider_configs) as Configs;const providers={deepseek:{model:configs.deepseek?.model??'',baseUrl:configs.deepseek?.baseUrl??'https://api.deepseek.com',configured:Boolean(configs.deepseek?.ciphertext||row.credential_ciphertext)},chatgpt:{model:configs.chatgpt?.model??'',baseUrl:configs.chatgpt?.baseUrl??'https://api.openai.com/v1',configured:Boolean(configs.chatgpt?.ciphertext)}};if(!['deepseek','chatgpt'].includes(row.provider))throw new Error('ai-settings-integrity');return {provider:row.provider,providers,model:providers[row.provider].model,baseUrl:providers[row.provider].baseUrl,enabled:row.enabled===1,configured:providers[row.provider].configured,unlimitedDailyUsage:row.unlimited_daily_usage===1,dailyRequestLimit:row.daily_request_limit,dailyTokenLimit:row.daily_token_limit,concurrentLimit:row.concurrent_limit,maxOutputTokens:row.max_output_tokens,revision:row.revision};
  }
  async configure(scope:Scope,raw:unknown):Promise<{status:'accepted'|'stale';settings:Settings}>{
    const value=studyObject(raw,['enabled','dailyRequestLimit','maxOutputTokens','expectedRevision','confirmCosts'],['unlimitedDailyUsage','dailyTokenLimit','concurrentLimit','providerKey','clearProviderKey','provider','model','baseUrl']);if(typeof value.enabled!=='boolean'||typeof value.confirmCosts!=='boolean'||value.enabled&&!value.confirmCosts)throw new Error('ai-cost-confirmation-required');
    studyCount(value.dailyRequestLimit,'daily-limit',1);studyCount(value.maxOutputTokens,'max-tokens',100);studyCount(value.expectedRevision,'expected-revision');const before=await this.getSettings(scope),unlimitedDailyUsage=value.unlimitedDailyUsage??before.unlimitedDailyUsage??false,dailyTokenLimit=value.dailyTokenLimit??before.dailyTokenLimit,concurrentLimit=value.concurrentLimit??before.concurrentLimit;if(value.unlimitedDailyUsage!==undefined&&typeof value.unlimitedDailyUsage!=='boolean')throw new Error('invalid-ai-budget');studyCount(dailyTokenLimit,'daily-token-limit',100);studyCount(concurrentLimit,'concurrent-limit',1);if(value.dailyRequestLimit>10||value.maxOutputTokens>2000||dailyTokenLimit>20000||concurrentLimit>2)throw new Error('invalid-ai-budget');
    if(value.providerKey!==undefined){studyText(value.providerKey,'provider-key',512);if((value.providerKey as string).length<8)throw new Error('invalid-provider-key');}if(value.clearProviderKey!==undefined&&typeof value.clearProviderKey!=='boolean')throw new Error('invalid-clear-provider-key');if(value.providerKey!==undefined&&value.clearProviderKey)throw new Error('invalid-provider-key-update');
    if(before.revision!==value.expectedRevision)return{status:'stale',settings:before};
    const provider=(value.provider??before.provider) as StudyAIProvider;if(!['chatgpt','deepseek'].includes(provider))throw new Error('invalid-ai-provider');
    const model=(value.model??before.providers[provider].model) as string,baseUrl=(value.baseUrl??before.providers[provider].baseUrl) as string;studyText(model,'ai-model',160,true);providerEndpoint({provider,baseUrl});
    if(value.enabled&&((!before.providers[provider].configured&&value.providerKey===undefined)||value.clearProviderKey===true))throw new Error('account-ai-key-required');
    const row=await this.q('SELECT provider_configs FROM account_study_ai_settings WHERE user_id=? AND library_id=?',...args(scope)).first<{provider_configs:string}>(),configs=JSON.parse(row!.provider_configs) as Configs;
    const encrypted=value.providerKey===undefined?null:await encryptAccountAiKey(this.encryptionKey,{...scope,libraryId:`${scope.libraryId}::${provider}`},value.providerKey as string),clear=value.clearProviderKey===true;
    configs[provider]={...configs[provider],model,baseUrl,...(encrypted??{})};if(clear){delete configs[provider]!.ciphertext;delete configs[provider]!.nonce;}
    // Legacy DeepSeek columns remain readable until that credential is explicitly replaced.
    const legacyEncrypted=provider==='deepseek'&&value.providerKey!==undefined?await encryptAccountAiKey(this.encryptionKey,scope,value.providerKey as string):null;
    const written=await this.q('UPDATE account_study_ai_settings SET provider=?,provider_configs=?,enabled=?,unlimited_daily_usage=?,daily_request_limit=?,daily_token_limit=?,concurrent_limit=?,max_output_tokens=?,credential_ciphertext=CASE WHEN ? THEN NULL WHEN ? IS NOT NULL THEN ? ELSE credential_ciphertext END,credential_nonce=CASE WHEN ? THEN NULL WHEN ? IS NOT NULL THEN ? ELSE credential_nonce END,revision=? WHERE user_id=? AND library_id=? AND revision=?',provider,JSON.stringify(configs),value.enabled?1:0,unlimitedDailyUsage?1:0,value.dailyRequestLimit,dailyTokenLimit,concurrentLimit,value.maxOutputTokens,clear&&provider==='deepseek'?1:0,legacyEncrypted?.ciphertext??null,legacyEncrypted?.ciphertext??null,clear&&provider==='deepseek'?1:0,legacyEncrypted?.nonce??null,legacyEncrypted?.nonce??null,before.revision+1,...args(scope),before.revision).run();
    const settings=await this.getSettings(scope);return{status:written.meta.changes===1?'accepted':'stale',settings};
  }
  async providerKey(scope:Scope,expectedRevision?:number,requestedProvider?:StudyAIProvider):Promise<string>{const settings=await this.getSettings(scope);if(expectedRevision!==undefined&&settings.revision!==expectedRevision)throw new Error('ai-settings-stale');const row=await this.q('SELECT credential_ciphertext,credential_nonce,provider_configs FROM account_study_ai_settings WHERE user_id=? AND library_id=? AND revision=?',...args(scope),settings.revision).first<{credential_ciphertext:string|null;credential_nonce:string|null;provider_configs:string}>();if(!row)throw new Error('ai-settings-stale');const provider=requestedProvider??settings.provider;if(!['deepseek','chatgpt'].includes(provider))throw new Error('invalid-ai-provider');const config=(JSON.parse(row.provider_configs) as Configs)[provider];if(config?.ciphertext&&config.nonce)return decryptAccountAiKey(this.encryptionKey,{...scope,libraryId:`${scope.libraryId}::${provider}`},config.ciphertext,config.nonce);if(provider!=='deepseek'||!row?.credential_ciphertext||!row.credential_nonce)throw new Error('account-ai-key-required');return decryptAccountAiKey(this.encryptionKey,scope,row.credential_ciphertext,row.credential_nonce);}
  async begin(scope:Scope,raw:unknown):Promise<{status:'accepted'|'completed'|'pending'|'failed';result?:unknown;errorCode?:string;settings:Settings}>{
    const value=studyObject(raw,['requestId','day','inputHash','trace'],['reservedTokens','expectedRevision']);if(value.expectedRevision!==undefined)studyCount(value.expectedRevision,'expected-revision');studyId(value.requestId,'request');if(!validPlanDay(value.day))throw new Error('invalid-plan-day');studyDigest(value.inputHash);
    await this.q("UPDATE account_study_ai_requests SET status='failed',error_code='ai-request-indeterminate' WHERE user_id=? AND status='pending' AND created_at<=datetime('now','-5 minutes')",scope.userId).run();
    const old=await this.q('SELECT * FROM account_study_ai_requests WHERE user_id=? AND library_id=? AND request_id=?',...args(scope),value.requestId).first<{input_hash:string;status:string;result_json:string|null;error_code:string|null}>(),settings=await this.getSettings(scope);
    if(old){if(old.input_hash!==value.inputHash)throw new Error('ai-request-conflict');if(!['pending','completed','failed'].includes(old.status))throw new Error('ai-request-integrity');
      if(old.status==='completed'&&!old.result_json||old.status!=='completed'&&old.result_json)throw new Error('ai-request-integrity');
      return{status:old.status as 'pending'|'completed'|'failed',...(old.result_json?{result:JSON.parse(old.result_json)}:{}),...(old.status==='failed'?{errorCode:old.error_code??'cloud-ai-provider-error'}:{}),settings};}
    if(value.expectedRevision!==undefined&&value.expectedRevision!==settings.revision)throw new Error('ai-settings-stale');const requestTrace=trace(value.trace);if(requestTrace.provider!==undefined&&!['deepseek','chatgpt'].includes(requestTrace.provider))throw new Error('invalid-ai-provider');if(!settings.enabled)throw new Error('account-ai-disabled');const reservedTokens=value.reservedTokens??settings.maxOutputTokens;studyCount(reservedTokens,'reserved-tokens',settings.maxOutputTokens);if(reservedTokens>100000)throw new Error('invalid-ai-reservation');
    const inserted=await this.q("INSERT INTO account_study_ai_requests(user_id,library_id,request_id,day,input_hash,operation_kind,model_id,prompt_version,rule_version,provider_id,status,reserved_tokens) SELECT ?,?,?,?,?,?,?,?,?,?,'pending',? WHERE (? IS NULL OR EXISTS(SELECT 1 FROM account_study_ai_settings WHERE user_id=? AND library_id=? AND revision=?)) AND (?=1 OR (SELECT count(*) FROM account_study_ai_requests WHERE user_id=? AND day=?) < ?) AND (SELECT count(*) FROM account_study_ai_requests WHERE user_id=? AND status='pending') < ? AND (?=1 OR (SELECT coalesce(sum(CASE WHEN status='pending' THEN reserved_tokens ELSE coalesce(usage_tokens,reserved_tokens) END),0) FROM account_study_ai_requests WHERE user_id=? AND day=?) + ? <= ?) ON CONFLICT DO NOTHING",...args(scope),value.requestId,value.day,value.inputHash,requestTrace.operationKind,requestTrace.modelId,requestTrace.promptVersion,requestTrace.ruleVersion,requestTrace.provider??'deepseek',reservedTokens,value.expectedRevision??null,...args(scope),value.expectedRevision??null,settings.unlimitedDailyUsage?1:0,scope.userId,value.day,settings.dailyRequestLimit,scope.userId,settings.concurrentLimit,settings.unlimitedDailyUsage?1:0,scope.userId,value.day,reservedTokens,settings.dailyTokenLimit).run();
    const saved=await this.q('SELECT input_hash,status,result_json,error_code FROM account_study_ai_requests WHERE user_id=? AND library_id=? AND request_id=?',...args(scope),value.requestId).first<{input_hash:string;status:string;result_json:string|null;error_code:string|null}>();if(!saved){if(value.expectedRevision!==undefined&&(await this.getSettings(scope)).revision!==value.expectedRevision)throw new Error('ai-settings-stale');const pending=await this.q("SELECT count(*) AS value FROM account_study_ai_requests WHERE user_id=? AND status='pending'",scope.userId).first<number>('value')??0,tokens=await this.q("SELECT coalesce(sum(CASE WHEN status='pending' THEN reserved_tokens ELSE coalesce(usage_tokens,reserved_tokens) END),0) AS value FROM account_study_ai_requests WHERE user_id=? AND day=?",scope.userId,value.day).first<number>('value')??0;if(pending>=settings.concurrentLimit)throw new Error('account-ai-concurrency-limit');if(!settings.unlimitedDailyUsage&&tokens+reservedTokens>settings.dailyTokenLimit)throw new Error('account-ai-token-limit');throw new Error('account-ai-daily-limit');}if(saved.input_hash!==value.inputHash)throw new Error('ai-request-conflict');if(inserted.meta.changes!==1)return{status:saved.status==='completed'?'completed':saved.status==='failed'?'failed':'pending',...(saved.result_json?{result:JSON.parse(saved.result_json)}:{}),...(saved.status==='failed'?{errorCode:saved.error_code??'cloud-ai-provider-error'}:{}),settings};return{status:'accepted',settings};
  }
  async complete(scope:Scope,requestId:string,inputHash:string,result:unknown,usageTokens=0):Promise<void>{
    studyId(requestId);studyDigest(inputHash);studyCount(usageTokens,'usage-tokens');const reservation=await this.q('SELECT reserved_tokens FROM account_study_ai_requests WHERE user_id=? AND library_id=? AND request_id=? AND input_hash=?',...args(scope),requestId,inputHash).first<number>('reserved_tokens');studyCount(reservation,'reserved-tokens');if(usageTokens>reservation){await this.q("UPDATE account_study_ai_requests SET status='failed',usage_tokens=?,error_code='ai-usage-exceeds-reservation' WHERE user_id=? AND library_id=? AND request_id=? AND input_hash=? AND status='pending'",usageTokens,...args(scope),requestId,inputHash).run();throw new Error('ai-usage-exceeds-reservation');}const resultHash=await studyHash(result);void resultHash;
    await this.q("UPDATE account_study_ai_requests SET status='completed',result_json=?,usage_tokens=?,error_code=NULL WHERE user_id=? AND library_id=? AND request_id=? AND input_hash=? AND status='pending'",canonicalizeJson(result),usageTokens,...args(scope),requestId,inputHash).run();
    const row=await this.q('SELECT status,result_json FROM account_study_ai_requests WHERE user_id=? AND library_id=? AND request_id=?',...args(scope),requestId).first<{status:string;result_json:string|null}>();if(!row||row.status!=='completed'||canonicalizeJson(JSON.parse(row.result_json!))!==canonicalizeJson(result))throw new Error('ai-request-completion-failed');
  }
  async fail(scope:Scope,requestId:string,inputHash:string,code:string):Promise<void>{studyId(requestId);studyDigest(inputHash);if(!/^[a-z0-9-]{1,80}$/.test(code))code='cloud-ai-provider-error';await this.q("UPDATE account_study_ai_requests SET status='failed',error_code=? WHERE user_id=? AND library_id=? AND request_id=? AND input_hash=? AND status='pending'",code,...args(scope),requestId,inputHash).run();}
}
