// @ts-expect-error Node contract tests use explicit extensions.
import {studyAIErrorCode} from './study-ai-errors.ts';
import type {StudyAIChatRequest,StudyAIService,StudyAISettings,StudyAISettingsInput,StudyAIStreamEvent,StudyAIProvider,StudyAIScope,StudyAIMessage} from './study-ai-types';
export type StudyAITransport=(action:'settings'|'configure'|'chat'|'models',value?:unknown,signal?:AbortSignal)=>Promise<unknown>;
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('ai-response-invalid');return value as Record<string,unknown>;}
export function parseStudyAISettings(raw:unknown):StudyAISettings{const wrapper=object(raw),v=object(wrapper.settings??wrapper);if(!['deepseek','chatgpt'].includes(String(v.provider))||typeof v.enabled!=='boolean'||typeof v.configured!=='boolean'||!Number.isSafeInteger(v.revision)||Number(v.revision)<0||typeof v.model!=='string'||typeof v.baseUrl!=='string')throw new Error('ai-settings-invalid');const providers=object(v.providers),clean={} as StudyAISettings['providers'];for(const p of ['deepseek','chatgpt'] as const){const c=object(providers[p]);if(typeof c.model!=='string'||typeof c.baseUrl!=='string'||typeof c.configured!=='boolean')throw new Error('ai-settings-invalid');clean[p]={model:c.model,baseUrl:c.baseUrl,configured:c.configured};}for(const field of ['dailyRequestLimit','dailyTokenLimit','concurrentLimit','maxOutputTokens'])if(!Number.isSafeInteger(v[field])||Number(v[field])<1)throw new Error('ai-settings-invalid');if(v.unlimitedDailyUsage!==undefined&&typeof v.unlimitedDailyUsage!=='boolean')throw new Error('ai-settings-invalid');return{unlimitedDailyUsage:v.unlimitedDailyUsage===true,provider:v.provider as StudyAIProvider,model:v.model,baseUrl:v.baseUrl,enabled:v.enabled,configured:v.configured,revision:v.revision as number,providers:clean,dailyRequestLimit:v.dailyRequestLimit as number,dailyTokenLimit:v.dailyTokenLimit as number,concurrentLimit:v.concurrentLimit as number,maxOutputTokens:v.maxOutputTokens as number,serverAvailable:wrapper.serverAvailable!==false&&v.serverAvailable!==false};}
async function decodeJson(value:unknown){if(value instanceof Response){if(!value.ok){let code='ai-request-failed';try{const body=object(await value.json());const message=body.error??body.message;if(typeof message==='string'&&/^[a-z0-9-]{1,80}$/.test(message))code=message;}catch{/* Malformed upstream errors stay generic. */}throw new Error(code);}return value.json();}return value;}
export async function* decodeStudyAIStream(response:Response,signal:AbortSignal):AsyncGenerator<StudyAIStreamEvent>{
 if(!response.ok){await decodeJson(response);return;}
 if(!response.headers.get('content-type')?.includes('text/event-stream')){const v=object(await response.json()),result=object(v.result),trace=object(result.trace);if(typeof result.text!=='string')throw new Error('ai-response-invalid');signal.throwIfAborted();yield{type:'delta',text:result.text};yield{type:'done',model:String(trace.providerModel??trace.modelId),provider:trace.provider as StudyAIProvider};return;}
 if(!response.body)throw new Error('ai-stream-missing');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',done=false;const abort=()=>{void reader.cancel();};signal.addEventListener('abort',abort,{once:true});
 try{while(!done){signal.throwIfAborted();const chunk=await reader.read();signal.throwIfAborted();buffer+=decoder.decode(chunk.value,{stream:!chunk.done});if(buffer.length>262144)throw new Error('ai-stream-limit');let match:RegExpExecArray|null;while((match=/\r?\n\r?\n/.exec(buffer))){const block=buffer.slice(0,match.index);buffer=buffer.slice(match.index+match[0].length);const data=block.split(/\r?\n/).filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(!data)continue;const event=object(JSON.parse(data));if(event.type==='error')throw new Error(studyAIErrorCode(event.error));if(event.type==='delta'&&typeof event.text==='string')yield{type:'delta',text:event.text};else if(event.type==='done'){done=true;yield{type:'done',...(typeof event.model==='string'?{model:event.model}:{}),...(['deepseek','chatgpt'].includes(String(event.provider))?{provider:event.provider as StudyAIProvider}:{}),...(Number.isSafeInteger(event.usageTokens)?{usageTokens:event.usageTokens as number}:{})};break;}else throw new Error('ai-stream-invalid');}if(chunk.done&&!done)throw new Error('ai-stream-incomplete');}}
 finally{signal.removeEventListener('abort',abort);await reader.cancel().catch(()=>{});reader.releaseLock();}
}
export function createStudyAIService({request}:{request:StudyAITransport}):StudyAIService{return{
 async models(value,signal){const raw=object(await decodeJson(await request('models',value,signal)));if(!Array.isArray(raw.models)||raw.models.length===0||raw.models.some(id=>typeof id!=='string'))throw new Error('ai-model-list-empty');return raw.models as string[];},
 async testConnection(value,signal){const started=Date.now();let text='',model=value.model;for await(const event of this.chat({requestId:`test:${crypto.randomUUID()}`,provider:value.provider,model:value.model,settingsRevision:value.revision,context:{id:'connection-test',title:'API连接测试'},messages:[{role:'user',content:'Reply with OK only.'}]},signal)){if(event.type==='delta')text+=event.text;else model=event.model??model;}if(!text.trim())throw new Error('ai-provider-error');return{provider:value.provider,model,latencyMs:Date.now()-started};},
 async settings(signal){return parseStudyAISettings(await decodeJson(await request('settings',undefined,signal)));},
 async configure(value,signal){const raw=object(await decodeJson(await request('configure',value,signal)));if(raw.status==='stale')throw new Error('ai-settings-stale');return parseStudyAISettings(raw);},
 async *chat(value,signal){signal.throwIfAborted();const raw=await request('chat',value,signal);signal.throwIfAborted();if(raw instanceof Response){yield*decodeStudyAIStream(raw,signal);return;}const result=object(object(raw).result),trace=object(result.trace);if(typeof result.text!=='string')throw new Error('ai-response-invalid');yield{type:'delta',text:result.text};yield{type:'done',model:String(trace.providerModel??trace.modelId),provider:trace.provider as StudyAIProvider};}
};}
export function createAccountStudyAIService(client:{aiWorkspaceRequest:StudyAITransport}):StudyAIService{return createStudyAIService({request:client.aiWorkspaceRequest});}
export function createLocalStudyAIService(options:{baseUrl:string;token:string;libraryId:string;fetcher?:typeof fetch}):StudyAIService{return createStudyAIService({request:async(action,value,signal)=>{
 let request=value;
 // Older Companions accept exercise context only; fold safe page text into that supported shape.
 if(action==='chat'&&value&&typeof value==='object'){
  const original=value as StudyAIChatRequest,c=original.context;
  request={...original,context:{id:c.id,title:c.title,question:[c.question,c.selection&&`选中内容：${c.selection}`,c.pageText].filter(Boolean).join('\n\n').slice(0,4000),...(c.learnerAnswer?{learnerAnswer:c.learnerAnswer}:{}),...(c.code?{code:c.code}:{}),...(c.errors?{errors:c.errors}:{})}};
 }
 const body=action==='settings'?{}:action==='configure'?{settings:value}:action==='models'?{selection:value}:{request};
 const response=await(options.fetcher??fetch)(`${options.baseUrl.replace(/\/$/,'')}/v1/ai/${action}`,{method:'POST',signal,headers:{'Content-Type':'application/json','X-Study-Loop-Session':options.token},body:JSON.stringify({libraryId:options.libraryId,...body})});
 if(action==='models'&&[404,501].includes(response.status))throw new Error('ai-companion-upgrade-required');return response;
}});}
export function studyAIHistoryKey(scope:StudyAIScope,provider:StudyAIProvider,conversation:string){return `study-ai-chat-v1:${JSON.stringify([scope.mode,scope.ownerId,scope.libraryId,provider,conversation])}`;}
export function readStudyAIHistory(storage:Pick<Storage,'getItem'>,key:string):StudyAIMessage[]{try{const value=JSON.parse(storage.getItem(key)??'[]');if(!Array.isArray(value))return[];return value.slice(-100).filter(m=>m&&typeof m.id==='string'&&['user','assistant'].includes(m.role)&&typeof m.content==='string'&&m.content.length<=50000).map(m=>({id:m.id,role:m.role,content:m.content,...(typeof m.model==='string'?{model:m.model}:{}),...(typeof m.contextId==='string'?{contextId:m.contextId.slice(0,240)}:{}),...(typeof m.contextTitle==='string'?{contextTitle:m.contextTitle.slice(0,160)}:{}),...(['deepseek','chatgpt'].includes(m.provider)?{provider:m.provider}:{})}));}catch{return[];}}
export function writeStudyAIHistory(storage:Pick<Storage,'setItem'>,key:string,messages:StudyAIMessage[]){storage.setItem(key,JSON.stringify(messages.slice(-100).map(({id,role,content,model,provider,contextId,contextTitle})=>({id,role,content,model,provider,contextId,contextTitle}))));}
export class StudyAIRequestGate{private controller:AbortController|null=null;private version=0;invalidate(){this.controller?.abort();this.controller=null;this.version++;}begin(){this.invalidate();const version=this.version;this.controller=new AbortController();return{signal:this.controller.signal,current:()=>version===this.version};}}
export type {StudyAIChatRequest,StudyAISettingsInput};

export function studyAIConversationMessages(messages:StudyAIMessage[]){return messages.filter(message=>message.content.trim()).slice(-30).map(({role,content})=>({role,content}));}
