import type {StudyItemVersion} from '../sync';
// @ts-expect-error TS5097: standalone Node contracts.
import {studyObject,studyId,studyDigest,studyText} from '../sync/index.ts';
// @ts-expect-error TS5097: standalone Node contracts.
import {parseCalculationSupport} from '../content/index.ts';
// @ts-expect-error TS5097: standalone Node contracts.
import {parseMathVariantMapping,type MathVariantMappingV1} from './mapping.ts';

/** Authored source preparation. Review must be performed by the publisher,
 * never generated by quoting arbitrary words or selecting a learner template. */
export type MathMappingPreparationV1={
    schemaVersion:1;snapshotId:string;mapping:MathVariantMappingV1;
    review:{sourceQuote:string;rationale:string};
};
export type MathMappingPreparationRecordV1={
    schemaVersion:1;preparation:MathMappingPreparationV1;
    provenance:{originGrantId:string;publishedAt:string};
    technicalValidation:{schemaVersion:1;templateVersion:1};
};
export function parseMathMappingPreparation(raw:unknown):MathMappingPreparationV1{
    const v=studyObject(raw,['schemaVersion','snapshotId','mapping','review']);
    if(v.schemaVersion!==1)throw Error('math-mapping-preparation-version');
    studyId(v.snapshotId,'snapshot');
    const mapping=parseMathVariantMapping(v.mapping);
    if(mapping.hashKind!=='content')throw Error('math-mapping-content-hash-required');
    studyDigest(mapping.parentContentHash);
    const review=studyObject(v.review,['sourceQuote','rationale']);
    studyText(review.sourceQuote,'source-quote',1000);studyText(review.rationale,'review-rationale',2000);
    return {schemaVersion:1,snapshotId:v.snapshotId,mapping,review:{sourceQuote:review.sourceQuote,rationale:review.rationale}};
}
const normalized=(conditions:string[])=>conditions.map(x=>x.trim().replace(/\s+/gu,' ').toLowerCase()).sort();
/** Binds review to complete original content. Technical validation cannot
 * determine whether the publisher's pedagogical judgment is correct. */
export function validateMathMappingPreparation(raw:unknown,item:StudyItemVersion|null):MathMappingPreparationV1{
    const p=parseMathMappingPreparation(raw),m=p.mapping;
    if(!item||item.kind!=='practice'||item.schemaVersion!==2||item.practice.questionType!=='calculation'
        ||item.itemKey!==m.parentItemKey||item.contentHash!==m.parentContentHash)throw Error('math-mapping-original-binding');
    studyText(item.practice.prompt,'original-prompt',16000);
    if(!item.practice.prompt.includes(p.review.sourceQuote))throw Error('math-mapping-review-quote-binding');
    const support=parseCalculationSupport(item.learningSupport);
    if(support.schemaVersion!==2||support.variantMappingId!==m.mappingId)throw Error('math-mapping-reference-binding');
    if(!support.conditions?.length||JSON.stringify(normalized(support.conditions))!==JSON.stringify(normalized(m.sourceConditions)))
        throw Error('math-mapping-source-conditions');
    return p;
}
